### ISSUE TITLE
Avoid little step edge

### ISSUE THREAD

**Issue by CamboimGabriel** [wbkd/react-flow#1010]
![image](https://user-images.githubusercontent.com/36650520/111502257-723b6680-8724-11eb-802e-b696a32346ea.png)

Hello, I'm using step edge but sometimes I dont need to use in "step" mode, so I'm trying to place the edge full "on center" without step but this little step remains on the edge, how can I remove it?

**Comment by CamboimGabriel** [comment]
up

**Comment by moklick** [comment]
Maybe rounding issues? I will take a look!

**Comment by CamboimGabriel** [comment]
is there any work around that I can do?

**Comment by moklick** [comment]
You can implement a custom edge based on the smooth step edge

**Comment by CamboimGabriel** [comment]
sounds hard e.e

**Comment by moklick** [comment]
Are you using `snapToGrid`? Can you create a codesandbox or a repo? I can't reproduce this.

**Comment by CamboimGabriel** [comment]
I'm not using snapToGrid, try changes the size of the components
![image](https://user-images.githubusercontent.com/36650520/112694180-aa4b5380-8e60-11eb-8fdb-b9b129fe716c.png)
I made all custom components with different sizes, The code is a lot big, its a big project, But If u want I can share the repo with you

**Comment by moklick** [comment]
As I said, I can't reproduce it. It's strange, because your nodes have the same height. If you can share your repo I will have a look.

https://user-images.githubusercontent.com/2857535/112696073-7afb0d80-8e85-11eb-8807-ff561dd9c2cf.mov

**Comment by CamboimGabriel** [comment]
@moklick here is the repo https://github.com/CamboimGabriel/frontend-movi I change to public for u look

**Comment by moklick** [comment]
This is still not reproducible for me. I tested it with Chrome and Firefox.

https://user-images.githubusercontent.com/2857535/112702525-18f5d480-8e94-11eb-9bcf-acee1158180a.mov

**Comment by CamboimGabriel** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/36650520/112702933-e89e3e00-8e73-11eb-8fb2-b5fc672ca9f1.gif)

Try with different type of nodes, sometimes with equal size nodes works well with me

**Comment by moklick** [comment]
Ok. When you nodes with different sizes this can happen. I checked your app again and it's the case that the handles are not on the same y position. That's why you get these little steps. I will not handle this case with the library. You will need to implement a custom edge. You can use the `getSmoothStepPath` with `borderRadius =0` of the [edge utils](https://reactflow.dev/docs/api/edge-utils/) to calculate the path. You can handle this case with something like this:

```javascript
if (Math.abs(sourceY - targetY) < 1) {
 sourceY = targetY
}
```

You can find an implementation of a custom edge here at the end of the page: https://reactflow.dev/examples/edges/
