### ISSUE TITLE
customisable controls?

### ISSUE THREAD

**Issue by TamjidTayeb** [wbkd/react-flow#1030]
Can we extends the controls component and add our own buttons to it ?

Would be really helpful,

thanks

**Comment by mikebarkmin** [comment]
I think that you can copy the content of this file https://github.com/wbkd/react-flow/blob/main/src/additional-components/Controls/index.tsx and create a custom component to your liking. 

The useZoomPaneHelper can be imported likes this: `import { useZoomPanHelper } from 'react-flow-renderer';`
The useStoreState and useStoreAction likes this: `{ useStoreState, useStoreActions } from 'react-flow-renderer';`

**Comment by TamjidTayeb** [comment]
great thanks a lot, I will make the component take a prop 'actions' which will be an array of icons and onclick actions so that you can add additional buttons to the controls. Would you be open to accept such a change if I submit a pr?

**Comment by mikebarkmin** [comment]
I am not a maintainer. ;)

**Comment by moklick** [comment]
As @mikebarkmin pointed out the best way is to reimplement the controls panel at the moment.

If you want to do a PR I would suggest the following:

* export a `ControlsButton` from the `Controls` component that one could use in order to get the current control button styling
* let the `Controls` component render `children` at the end of the buttons

with this API it's easy to handle active states and it's more flexible.

**Comment by moklick** [comment]
released in v9.4.0
