### ISSUE TITLE
Improve deleteKeyCode to accept array

### ISSUE THREAD

**Issue by clementloridan** [wbkd/react-flow#1054]
I want to delete my elements with Backspace (keyCode: 8) and Delete (keyCode: 46)

So possibility to accept this:
`
deleteKeyCode={[8, 46]}
`

OR

`
deleteKeyCode={['Backspace', 'Delete']}
`

**Comment by moklick** [comment]
Maybe it's possible to release this feature without a breaking change when we don't support multiple `keyCodes` and only make `key` and `code` available for key combinations.

**Comment by clementloridan** [comment]
deprecated keyCode anymore?

I don't understand why it will be a breaking change?

If needed, I can help :)

**Comment by moklick** [comment]
Right now you can pass a single `event.key` or `event.keyCode` ('Backspace' / 8) as a key code. Since using [`keyCode` is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and it's more complicated to build, I implemented a new version where you can pass a single `event.key` or `event.code` or multiple ones but no `event.keyCodes` anymore.

**Comment by clementloridan** [comment]
Ok so what is the next step to have this on npm? Maybe on canary version?

**Comment by clementloridan** [comment]
@moklick Any update? :)

**Comment by moklick** [comment]
This has a very low priority. If you need it now, you can implement it with https://github.com/JohannesKlauss/react-hotkeys-hook for example.

**Comment by clementloridan** [comment]
Hey @moklick I test the branch refactor/keys. For me all is good 👍

**Comment by NikolMarg** [comment]
Also interested in this one. I've already done an implementation with a hook, but since I have an input inside my nodes, it was mistaking the Delete/Backspace for node deletion. Fix was easy but there are more issues (eg. when deleting multiple nodes with Shift) so I'd prefer a cleaner solution like proposed above.

**Comment by Ark-kun** [comment]
I've created a PR to allow multiple keys to be specified: https://github.com/wbkd/react-flow/pull/1281

**Comment by moklick** [comment]
I will close this. It's already built into the next version which can be tested with `npm install react-flow-renderer@next`
