### ISSUE TITLE
How to export as bpmn.js xml format

### ISSUE THREAD

**Issue by nfwyst** [wbkd/react-flow#1112]
I want to save the json data as xml format that match the bpmn standard, but there is introduce in the document

**Comment by leejustin** [comment]
If you want to convert JSON data to XML, you can use available libraries like https://www.npmjs.com/package/xml-js

You'd have to write your own mapper to have it match the BPMN standard ( https://www.omg.org/spec/BPMN/2.0/#documents ) because this library and BPMN don't have 1-to-1 mappings between objects. It looks like BPMN has very specific modeling elements whereas this library is more generic with a concept of nodes and edges. The elements in BPMN would be a subset of the capability provided by this library.

**Comment by nfwyst** [comment]
bro, is there any built in support like https://github.com/didi/LogicFlow/tree/master/packages/extension/src/bpmn-adapter?  @moklick

**Comment by moklick** [comment]
No there are no adapters. You need to implement them by yourself.
