### ISSUE TITLE
Feature request: Export / Save options png & svg

### ISSUE THREAD

**Issue by Luttik** [wbkd/react-flow#1286]
Hi all,

I love this library, not just the functionalities but also the standard look & feel. For me, this means that I'd love to be able to export react-flow visuals (preferably as SVG's) for use in presentations and documents. And I also see a big use-case here for the computer science world where they currently use a lot of Graphviz, it'd be great if this could be a lib that we can use both for interactive demos as well as for reports and papers.

**Comment by nielsuit227** [comment]
Would love to see this as well!

**Comment by moklick** [comment]
Hey @Luttik 

this is a great idea but React Flow contains DOM and SVG nodes. This makes it relatively hard to render it as a SVG (we have inputs and selects in our nodes for examples). In order to render a flow as a png we would need to have a server side puppeteer instance or something like that or try to use html2canvas. However this is not a feature I would like to add to React Flow. A separate package for exporting flows would be nice!

**Comment by Rudrava** [comment]
@moklick is there any other lib for exporting the flow as a png as you said ?

**Comment by moklick** [comment]
I've created a ["Download Image" example](https://reactflow.dev/docs/examples/misc/download-image/) that uses [html-to-image](https://github.com/bubkoo/html-to-image).
