### ISSUE TITLE
State management

### ISSUE THREAD

**Issue by moklick** [wbkd/react-flow#1378]
This is a big topic. We started with easy-peasy, because we made good experience with that library. After some time we realized that it's a bit of an overhead so we dropped it. Since it's built on redux, we switched to redux. Now we would really like to get rid of the reducer, action creator boilerplate stuff and find a state management library that helps us to optimize renderings and get a better performance. Zustand, Recoil and Mobx are on our list but we are open for suggestions.

**Comment by mikebarkmin** [comment]
I personally would lean to Zustand. I think it is a great library, which is easy to use and performant. Another option could be [XState](https://github.com/statelyai/xstate). It uses a state machine to manage the state.

**Comment by RickeyWard** [comment]
A common timewaster I've witnessed a lot is jumping back and fourth between state libraries. They will all come with their own overhead and boilerplate. The question is is it really worth it to change it? Also consider that redux will make it much easier to implement an internal undo/redo stack than some of those other libraries.

**Comment by laubonghaudoi** [comment]
What about Jotai? It is similar to recoil and looks very promising.

**Comment by bentron2000** [comment]
I started a while ago with EasyPeasy (which was great up to a point) - but after a while we switched to Recoil and it has been pretty good on the whole. There are a few cases that are a little tricky to work with that seem to be solved in another lib called [hookstate](https://hookstate.js.org) - so maybe add that to the consideration list.
PS. I LOVE this library

**Comment by fedulovivan** [comment]
Documentation still states that easy-peasy is under the hood.

**Comment by meatflavourdev** [comment]
https://hookstate.js.org/ is consistent with the school of thought that prefers consequential libraries like a state manager to, "Think in React" and to remain consistent and build upon what users already know from knowing React.

**Comment by meatflavourdev** [comment]
We know you will learn the Hookstate library API very quickly without reading much (if any) of the documentation. The following will help you get started in minutes:

---
## #Getting started ([from Docs](https://hookstate.js.org/docs/getting-started/))

Intuitive API. Most things will be self-explanatory. More in depth description will always be there.
Code samples in each section are self-contained, complete and interactive. So, jump to the relevant section, copy-paste a sample to your app and extend it as needed.
Intellisense by IDE. If your project is in Typescript, you will benefit a lot as type inference of the API functions supports any complexity of data structures of your states. Of course, you can also use it from plain javascript.
Complete demo application. There is a Todo-list-like complete demo application built with Hookstate. It uses and demonstrates most of the core features of Hookstate. It gives an example of how to organise your project. You may follow the example or use any other module-composition structure. Here it is running in an iframe:

**Comment by pf-costa** [comment]
I've implemented copy/paste and undo/redo, in my project, using the Zustand and Zundo libraries. It was very straightforward and intuitive. However, since that for each change, that I perform in the diagram, I'm storing the whole diagram information over and over again in an array. Thus, the browser's memory consumption skyrockets after a while, and the whole user experience suffers from this. For the copy/paste I would suggest that we only store the delta, i.e. the diff between one change and another. Since the library uses Redux, it should be feasible. As we can see, the redux-devtools already has this behavior. Perhaps we can extrapolate some ideas from it? Would be glad to help.

**Comment by RickeyWard** [comment]
@pf-costa It depends on how aggressively you use your global state. Zundo just sticks every change in there some things should be context sensitive. The undo stack should also have a practical limit. Because no one really "undoes" 2000 changes. It only becomes an issue if you store large things in your node state like audio or images but 50 undos is more than enough for most users, though that could be configurable just not unbounded by default.

**Comment by NurbekGithub** [comment]
valtio
