### ISSUE TITLE
Use of zIndex to order components causes problems with ReactXP

### ISSUE THREAD

**Issue by mikeestee** [wbkd/react-flow#1421]
Hi,

We're using ReactXP in our app and react-flow. The use of zIndex to manage the paint ordering for the react-flow canvas is causing problems with our tooltips, context menus, and other components which rely on the mouse events being routed correctly.

The rendering for react-flow, strictly speaking, doesn't need to use the zIndex for layout. Would you consider updating the framework to using the layout order instead?

My understanding of the problem is that forcing the zIndex creates a new "Stacking Context" which can eat mouse events.

There are many behaviors we're seeing, but an easy one to replicate is to have a custom node with a ReactXP Popup in it.
https://microsoft.github.io/reactxp/docs/apis/popup.html

**Comment by datoslabs** [comment]
@mikeestee , you can affect node's `zIndex` "at-rest" via the style property/attribute under node option, eg

```
{
  id: '1',
  type: 'input',
  data: { label: 'Node 1' },
  position: { x: 250, y: 5 },
  style:{zIndex:'unset'},
}
```
However, when a node is selected, its `zIndex` is increased to a higher value than default as it's needed during drag; without this and simply relying on layout order, the node being dragged could fall behind another resting node and would cause other UX issues.  I have only recently come across mouse events being suppressed due to "incorrect" relative `zIndex` value when I am trying to implement a container/grouping node (ie detect onMouseEnter event when a node is being dragged over a container/grouping node).  

FYI, I saw your other posts in the discussion section about grouping nodes.  Since I also need the same functionality, I began implementing a custom grouping node and encountered zIndex mouse event problem, saw this familiar issue, and decided to chime in.  I am experimenting with "raising" transparent `divs` with high `zIndex` value, as needed, to act as my mouse event sink; hope this helps.

**Comment by datoslabs** [comment]
@mikeestee , with regards to specifically showing a popup anchored to a node, have you considered using a technique similar to [Material UI's Portal](https://material-ui.com/components/portal/) implementation?  I am not familiar with ReactXP but as far as I know, it is a fairly common practice to create popups in an independent dom tree and reposition it relative to an anchor element (which ReactXP seem to support) so as to eliminate the need to modify/restructure `zIndex` of existing elements.  Using Material UI, I have not had any issues with mouse events in a popup opened from a React-Flow node.

**Comment by mikeestee** [comment]
I think elevating the index is fine for the dragging event cycle, as that should be living within a mouseDown/Up pair. However, there's nothing stopping react-flow from rendering the selected elements in any given order so strictly speaking, it's not necessary, just convenient.

Thank you for the suggestions though!

I have the following overrides in my css for managing the zIndex, this was my workaround for the tooltip problem.

```css
.react-flow__renderer {
    z-index: auto;
}

.react-flow__pane {
    z-index: auto;
}

.react-flow__background {
    z-index: auto;
    pointer-events: none;
}
```

I think the react-flow__pane element is where the issue is coming from. it needs to capture events to handle zoom/pan, but they don't seem to keep propagating out to the container where they could clear context menu clicks or the like.

**Comment by mikeestee** [comment]
When I remove the mouseDown handler from `react-flow__pane`:

![image](https://user-images.githubusercontent.com/48497605/128563215-3709b67f-4049-4e9d-b4b5-558f051d2437.png)

ReactXP is able to get events again. Unfortunately, this breaks the click-zoom/pan interaction in react-flow. This suggests that if I add a `RX.PopUp.clearAll()` to the mouse down handler for ZoomPan, it should clear the RX popup machinery when the users starts a zoom/pan.

Will try that and report back.

**Comment by mikeestee** [comment]
Adding these `dismissAll()` calls to the panning handlers clears up the behavior.

```
protected _onMoveStart = (xform?: FlowTransform): void => {
        // NOTE: clear any outstanding Popup menus
        // we need to do this here as react-flow__pane will eat the mouse events
        // ReactXP will use to dismiss context menus.
        RX.Popup.dismissAll();
    };

    protected _onPaneContextMenu = (e: React.MouseEvent): void => {
        // clear any outstanding Popup menus, see _onMoveStart
        RX.Popup.dismissAll();
    };
```
