### ISSUE TITLE
Drag and click nodes

### ISSUE THREAD

**Issue by dominikspiertz** [wbkd/react-flow#1457]
Hello dear react flow team,
we are currently working on the interaction to move the diagram for our users. There are multiple ways to move the position of the diagram and we are trying to find the most native implementation possible. Therefor our users can interact with our diagram on mobile as well as on desktop devices. To move the diagram around it is possible to drag the pane and move the diagram where desired. The only thing that we cannot yet achieve, is the dragging of the diagram if you touch a node instead of the pane. For example, if a user interacts on a mobile phone, it is common that you can drag everywhere on a draggle area. By now our users need to avoid, trying moving the diagram by accidentally selecting a node and can instead only touch in between nodes. I am aware that there is an option called `elementsSelectable` that we can set to `false`. This would be the perfect behaviour if we only had representational nodes. In fact our interaction on click of the nodes is essential to our application. We show the data of this node to view and change it accordingly. Is there somehow a way that it would be possible to track down an `onClick` as well as an `onDragStart` event for nodes to get the desired effect?
Thanks in advance

**Comment by datoslabs** [comment]
> The only thing that we cannot yet achieve, is the dragging of the diagram if you touch a node instead of the pane.

Are you trying to track the movement of a node and programmatically pan the canvas when the node is dragged towards an edge or dragged off the screen?  If so, you can track the mouse position in `onNodeDrag` against `.react-flow` element's `BoundingClientRect` and programmatically pan the canvas via 
```
const d3Zoom = useStoreState((s) => s.d3Zoom);

const onNodeDrag = (event, node) => {
  //logic to determine the direction and how much to pan based on drag 
  d3Zoom.translateBy(
              d3Selection,
              -(deltaX / currentZoom) * panOnScrollSpeed,
              -(deltaY / currentZoom) * panOnScrollSpeed
            );
  ...
}
```
You can reference [`ZoomPane` component src code](https://github.com/wbkd/react-flow/blob/4b043bceccf41ae1edbd52e2919e1bf5a65aef99/src/container/ZoomPane/index.tsx) for how to pan the canvas and [`DragNDrop` example](https://github.com/wbkd/react-flow/blob/4b043bceccf41ae1edbd52e2919e1bf5a65aef99/example/src/DragNDrop/index.tsx) for how to obtain the mouse position in `onNodeDrag`.

> In fact our interaction on click of the nodes is essential to our application. We show the data of this node to view and change it accordingly. Is there somehow a way that it would be possible to track down an `onClick` as well as an `onDragStart` event for nodes to get the desired effect?

As far as detecting when a node is clicked, you can use built-in `onElementClick` interaction.  However, be warned that both `onElementClick` and `onNodeDragStart` gets fired at the same time and what differentiates node click from node drag is whether the node is moved after the click (in other words, a node drag will subsequently trigger the onNodeDrag event while node click won't).  For this reason, I would suggest creating a custom node with a `<div onClick={...}>` instead of relying on `onElementClick` to trigger the node click callback.

**Comment by TitoGrine** [comment]
Hey @dominikspiertz, if I understand correctly, you want the pan by click and dragging to work everywhere on the pane, even if the click happens inside a node, but you also want the nodes to be clickable.

This is not straight forward to do in React Flow, I have a solution for you, but it has its drawbacks.
In order for React Flow to allow panning in the whole pane, no matter where clicks happen, it needs to not have any elements listening to mouse events, this includes clicking, scrolling, hovering, etc. To do this, you need to set the following to false in your `ReactFlow` component:

```js
<ReactFlow
      elements={elements}
      ...
      nodesDraggable={false}
      nodesConnectable={false}
      elementsSelectable={false}
>
```
 
With this, you should be able to pan around everywhere on the pane. If not, make sure you don't have custom elements with `onClick` events or CSS rules like `pointer-events: all`.
 
Now, in order to have the nodes clickable, we must create a handler for `onPaneClick` that will read the mouse click coordinates, convert them to the same coordinate set as the nodes, and check whether the position intersects any of the nodes bounds. Something like the following:

```js
const { project } = useZoomPanHelper();

...

const onPaneClick = (event) => {
      const boundingBox = event.target.getBoundingClientRect();

      const viewport_x = event.pageX - boundingBox.left;
      const viewport_y = event.pageY - boundingBox.top;

      const { x, y } = project({ x: viewport_x, y: viewport_y });
      
      ...
}
``` 

If your ReactFlow pane's top left corner matches the browser window, then you don't need to get the `boundingBox` and you can directly project the `pageX` and `pageY` coordinates.
Once you have these coordinates you just need to iterate through all your nodes and see if it collides with any node bounds.

I created a [codesandbox](https://codesandbox.io/s/react-flow-all-around-panning-f2tvi?file=/src/App.js:844-876) with a simple example that should be enough to get the picture.

Now, this has two main drawbacks that may or may not be an issue in your use case:
 1. Every time a user clicks the pane you will be checking for collisions in all your nodes. If you're dealing with less than a few hundred nodes it really shouldn't affect performance. But as the number increases it can become more of a problem. However, if you graph has some sort of structure where you can take advantage of a divide and conquer approach, you can work around this issue.
  2. Perhaps the biggest issue is that you can't have any sort of other interactions between mouse events and the elements. This means you can't have node/edge dragging, add/delete connections, on hover effects like tooltips, scrolling inside nodes, etc. Again, for your use case, this might not be an issue at all, but it's something to be aware.
  
Hope this helps!

**Comment by TheColorman** [comment]
I am now running into a similar problem. I want the user to be able to drag to pan anywhere on the screen, including on nodes, but I still want nodes to be selectable and register hover.
So, if you start dragging over a node, it'll pan, but if you click the node it will become selected, and hovering also works.
This behavior seems relatively complex, but would it be doable?

**Comment by Holybasil** [comment]
In fact, `NoPanClassName` is added to node by default so panning does not allowed on nodes.


```js
// src/components/Nodes/wrapNode.tsx
const nodeClasses = cc([
      'react-flow__node',
      `react-flow__node-${type}`,
      noPanClassName,     // here
      className,
      {
        selected,
        selectable: isSelectable,
        parent: isParent,
      },
]);

// src/containers/ZoomPane/index.tsx
// event.type === "mousedown"
if (isWrappedWithClass(event, noPanClassName) && event.type !== 'wheel') {
        return false;
}
```

Is it possible to optionally add class names to Node or Edge. 
This allows to pan on the node when `panOnDrag` is set to true while `nodesDraggable` and `elementsSelectable` are both false .

Here is a possible use case.
```js
const [mode, setMode] = useState(1)
<ReactFlow 
    nodesDraggable={mode === 1}
    elementsSelectable={mode === 1}
    panOnDrag={mode === 2}
    possibleAttribute={mode === 2}
    >
</ReactFlow>
```

**Comment by TheColorman** [comment]
@datoslabs We're looking for the ability for nodes to be selectable, while also panning the screen when clicking+dragging on the nodes, not dragging the nodes themselves.

**Comment by datoslabs** [comment]
Please disregard my previous comments, @Holybasil's recommendations/findings would work if implemented.

**Comment by agusmarracomulesoft** [comment]
Does not seem to be working for me when `onNodeClick` is specified, I had to manually remove the `nopan` class in order to be able to trigger click events on the nodes while also be able to pan a group node for example.

**Comment by moklick** [comment]
This behaviour will change with the next major release. From v11 on it will we possible to drag the pane when a nodes are not draggable. Either because the node option `draggable` is `false` or because `nodesDraggable` is `false`. Would this solve your issue @dominikspiertz ?

**Comment by croissantspectacular** [comment]
how can i test this fix in a project of mine that is currently using v10? it seems like #2370 is related to this
