### ISSUE TITLE
can't change the node color onclick

### ISSUE THREAD

**Issue by Shafahummer** [wbkd/react-flow#1481]
How to change the color of nodes on clicking on the custom  handle nodes, i think it is not re-rendering on elements value change.

**Comment by TitoGrine** [comment]
I suspect the problem is because you are not creating a new object when changing the styling and thus react flow doesn't know things changed. In the documentation there's the following:

![image](https://user-images.githubusercontent.com/36516031/131525323-4310ab32-a4e4-4382-acea-8a4830361ac5.png)

You can check the [update node example](https://reactflow.dev/examples/update-node/).
Hope this helps!

**Comment by moklick** [comment]
Thanks @TitoGrine.

Hey @Shafahummer please use the issues section for issues and not for questions about the general usage. Thanks!
