### ISSUE TITLE
tree support

### ISSUE THREAD

**Issue by truedrug** [wbkd/react-flow#1482]
Hey Guys,

Is there any library using react-flow and having tree support like [react-d3-tree](https://bkrem.github.io/react-d3-tree-demo/)?

I am using react-d3-tree library at the moment, but it just lacks one thing ie., doesn't provide any scrollbars when `svg` overflows the container. Other than that, this library pretty much handles the opening, closing of tree nodes also handles the space adjustments

At first, I tried `react-flow`, but failed on the implementation of space adjustments when multiple nodes overlap upon opening the tree nodes

Can someone help here please?

TIA

**Comment by moklick** [comment]
Hey @truedrug 

there is no built-in layouting but you can use any library you want for it.
We are using [dagre](https://github.com/dagrejs/dagre) (unfortunately deprecated since a few months) in our example https://reactflow.dev/examples/layouting/ . If you need to support more complex layouts I can also recommend [elkjs](https://github.com/kieler/elkjs). I hope it helps!
