### ISSUE TITLE
is the any way to fix this

### ISSUE THREAD

**Issue by Azim-Ahmed** [wbkd/react-flow#1516]
![image](https://user-images.githubusercontent.com/67516192/133915640-6c47c7ac-1078-46b2-babc-b64cd37cfc62.png)

Arrow Routing ---> this looks awkward

**Comment by Ipicky22** [comment]
Hi @Azim-Ahmed !

Can you share your code?
The solution could be to create a customEdge, and calculate the centerY manually.
I refer you to another issue where I explain this, [1642](https://github.com/wbkd/react-flow/issues/1642)

And I advise you to change the name of your issue, so that it is clearer and that other users come across your issue more easily.

I hope I have been helpful.

**Comment by moklick** [comment]
@Ipicky22 thanks for your input. 

@Azim-Ahmed as @Ipicky22 pointed out the only solution is to come up with a custom edge routing.
