### ISSUE TITLE
Pane position reset on remount

### ISSUE THREAD

**Issue by dstoyanoff** [wbkd/react-flow#1521]
Hello,
I have the following problem, not sure if it's a bug, desired behavior or I am doing something wrong.

I have a component, that can conditionally render two things - either the react flow or another component. All of this is wrapped in ReactFlowProvider higher in the hierarchy. 

When the user chooses one of the node types, he has the option to switch the view to the alternative component. When going back however, the pane position is getting reset, which reset all the navigation that the user did.

I've created a sandbox illustrating this - https://codesandbox.io/s/react-flow-demo-forked-ohp56?file=/src/App.js

1. Move the pane (not the node!)
2. Click on the toggle button to hide the flow (show alternative view)
3. Click back the toggle button to bring back the flow

**Expected result**: The pane should persist it's state, because the ReactFlowProvider was not re-rendered
**Actual result**: The pane is reset to initial state and this jump is noticable in the UI

**Comment by datoslabs** [comment]
`ReactFlowProvider` is a context and does not store state.  If `ReactFlow` component is unmounted, you can reference the [Save and Restore example](https://reactflow.dev/examples/save-and-restore/) to export the internal state and restore when you toggle back.

**Comment by dstoyanoff** [comment]
Thanks for the suggestion.

What I can see however is that the ReactFlowProvider creates the Redux store. When ReactFlow component is rendered in a tree where ReactFlowProvider exists, it will not create the store, but just render its children. That's why I thought that having the ReactFlowProvider up in the tree where both components render should be sufficient to preserve the state.

What I see however is that there is a small difference in initializing the store. In the Provider, the store is configured on demand, while in the ReactFlow component, an already configured instance is taken, which might be the reason I am experience this

**Comment by Nogias9x** [comment]
In my case, I have 2 tabs of flows, and users can freely switch between these tabs. If a tab is not selected, I want to hide that tab-pane and its flow with `visibility: hidden` on the tab-pane, so that current states of flows are not reset.
But then the inactive tab-pane is disappear but its flow is still. The flow seems not belong to the tab-pane.

I will try restoring state for now then.

**Comment by moklick** [comment]
@dstoyanoff This is the desired behaviour. We are resetting the store on unmount but I understand that it's a bit inconvenient here. What do you think about an `resetOnUnmount` prop?

**Comment by moklick** [comment]
As explained above this is the expected behaviour and actually I don't want to introduce another new prop. there are way too many already :D So, in order to achieve this, you need to store the viewport with help of `onMoveEnd` and then use that viewport for `defaultPosition` and `defaultZoom` when you mount the flow.
