### ISSUE TITLE
Cannot change node height or width dynamically

### ISSUE THREAD

**Issue by ShafahJiitak** [wbkd/react-flow#1586]
How to dynamically change the node height or width dynamically if the text inside the node is an input field

**Comment by huttj** [comment]
I'm got stuck on a similar issue. I figured out how to do it, but it feels like it could be a lot easier if there was an API to set the dimensions of a node programmatically.

I am using the [dagre](https://reactflow.dev/examples/layout/dagre) layout, which seems to require me to keep track of the widths and heights so I can sync them to the graph (because they're not static, like in the example). I'm doing that with `node.width` and `node.height`.

I couldn't figure out how to grow the height based on the amount of text inside the text area _and_ have a resize handle on the node. They seem to conflict with each other.

I had to essentially set up a separate variable with a two way sync—when the area should increase, I increase my div height, which I guess React Flow picks up and increases the size of the Node. And then when the resize handle emits a resize event, I adjust my height accordingly.

It works, but I feel like it's a lot of extra work.

**Comment by imabp** [comment]
This problem still exists. Not sure why the owners are closing these type of issues, instead of discussing a better approach towards the problem, instead of hacky workarounds like css or resize observer.

Above Resize observers may not scale well when you have complex graphs, and definitely impacts performance in complex enterprise level applications.

**Comment by dlvhdr** [comment]
@moklick could you take a look at this? we're also experiencing this.
