### ISSUE TITLE
React flow connection between two nodes doesn't appear while using custom Node

### ISSUE THREAD

**Issue by reygj** [wbkd/react-flow#1595]
I have this custom Node on my react flow app. Following this example here (end of the page for custom Node code): https://reactflow.dev/examples/custom-node/

I connect 2 nodes with a simple data and the node and rendered but no the arrow that connects them. It's not the style and transparency and I need that code to now show the dots.

Here's the sandbox: https://codesandbox.io/s/jovial-firefly-v5ddv

```
const Node = (data) => {
  return (
    <div
      style={{
        fontSize: 12,
        textAlign: "left",
        height: 120,
        width: 240,
        backgroundColor: "#fff000",
        color: "black",
        boxShadow: "0 5px 8px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19)"
      }}
    >
      {data.data.name}
      <Handle
        type="target"
        position="top"
        style={{
          backgroundColor: "transparent",
          border: 0
        }}
      />

      <Handle
        type="source"
        position="bottom"
        style={{
          backgroundColor: "transparent",
          border: 0
        }}
      />
    </div>
  );
};

```

**Comment by moklick** [comment]
Hey @reygj 

there are no initial edges in your example (the elements array only contains two nodes) and you didn't implement the `onConnect` function. Explanation: https://reactflow.dev/docs/getting-started/#basic-functionality

**Comment by Dhrutika1891** [comment]
import useGraphLayout from 'pages/WorkflowBuilder/hooks/useGraphLayout'
import { useState, useCallback, useEffect, useContext } from 'react'
import ReactFlow, {
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  Node,
  Edge,
  NodeChange,
  EdgeChange,
  Connection,
  Controls,
  Background,
  useReactFlow,
  SetCenterOptions,
  Viewport,
} from 'reactflow'
import 'reactflow/dist/style.css'
import { useSearchParams } from 'react-router-dom'
import { BuilderTemplate, getTemplate } from '../model'
import Loading from './Loading'
import DecisionResponseNode from './nodes/DecisionResponseNode'
import StartNode from './nodes/StartNode'
import useAnalyticsManager from 'hooks/useAnalyticsManager'
import { WorkflowData } from 'models/Workflow'
import StepNode from './nodes/StepNode'
import StepDetailsAside from './StepDetailsAside'
import { WorkflowBuilderContext } from '../workflowBuilder-context'
import {
  createStartNode,
  generateNodesFromWorkflowData,
} from '../helpers/workflowApiLoading'
import TerminalNode from './nodes/TerminalNode'

const nodeTypes = {
  Start: StartNode,
  Step: StepNode,
  DecisionResponse: DecisionResponseNode,
  Terminal: TerminalNode,
}
const proOptions = { account: 'paid-pro', hideAttribution: true }
const defaultViewport: Viewport = {
  x: window.innerWidth * 0.5,
  y: window.innerHeight * 0.2,
  zoom: 0.6,
}
function Flow() {
  const { setCenter, fitView } = useReactFlow()
  const {
    workflowId,
    workflowData,
    loading,
    setLoading,
    syncWorkflowData,
    setSelectedStepId,
  } = useContext(WorkflowBuilderContext)
  const [searchParams, setSearchParams] = useSearchParams()

  const [loadedWorkflowId, setLoadedWorkflowId] = useState<string>()
  const [nodes, setNodes] = useState<Node[]>([createStartNode()])
  const [edges, setEdges] = useState<Edge[]>([])
  const [centerNodeId, setCenterNodeId] = useState<string | undefined>('Start')
  const trackAnalytics = useAnalyticsManager()

  // Loading
  useEffect(() => {
    if (workflowId && loadedWorkflowId !== workflowId && workflowData) {
      setLoading(true)
      setLoadedWorkflowId(workflowId?.toString())
      let workflowToLoad = workflowData

      // If we should load from a template then fetch its data
      const templateParam = searchParams.get('template') as BuilderTemplate
      let template: WorkflowData | undefined = undefined
      if (templateParam) {
        template = getTemplate(templateParam)
        if (template) {
          workflowToLoad = {
            ...template,
            id: workflowData.id,
          }
          trackAnalytics('Add Templated Workflow Button', {
            'Template Name': template.title,
            'Workflow Collection ID': workflowData.workflow_collection_id,
          })

          searchParams.delete('template')
          setSearchParams(searchParams)
        }
      }

      // Load the nodes and edges
      if (template) {
        // If we loaded from a template we will need to save these new steps to the server
        syncWorkflowData(workflowToLoad)
      } else {
        const { nodes, edges } = generateNodesFromWorkflowData(workflowToLoad)
        setEdges(edges)
        setNodes(nodes)
        setLoading(false)
      }
    }
  }, [
    loadedWorkflowId,
    workflowId,
    workflowData,
    searchParams,
    setSearchParams,
    fitView,
    setCenter,
    setLoading,
    trackAnalytics,
    syncWorkflowData,
  ])

  // this hook handles the computation of the layout once the elements or the direction changes
  // because React Flow only needs the position of the nodes, there is no need to return the edges here
  const layoutedNodes = useGraphLayout(nodes, edges)

  const onNodesChange = useCallback(
    (changes: NodeChange[]) => {
      setNodes((nds) => applyNodeChanges(changes, nds))
    },
    [setNodes]
  )
  const onEdgesChange = useCallback(
    (changes: EdgeChange[]) => {
      setEdges((eds) => applyEdgeChanges(changes, eds))
    },
    [setEdges]
  )
  const onConnect = useCallback(
    (connection: Connection) => setEdges((eds) => addEdge(connection, eds)),
    [setEdges]
  )

  const centerOnNode = useCallback(
    (node: Node) => {
      const centerOptions = { duration: 600, zoom: 0.7 } as SetCenterOptions
      setCenter(
        node.position.x + (node?.width ?? 0) * 0.5,
        node.position.y + (node?.height ?? 0) + window.innerHeight * 0.25,
        centerOptions
      )
    },
    [setCenter]
  )

  // See if we can start the centerOnNode function
  useEffect(() => {
    // We only want to center on the centerNode once everything has a size
    if (loading || !layoutedNodes.every((n) => !!n.width)) return
    const centerNode = layoutedNodes.find((n) => n.id === centerNodeId)
    if (centerNode?.height !== undefined && !!centerNode?.position.x) {
      centerOnNode(centerNode)
      setCenterNodeId(undefined)
    }
  }, [layoutedNodes, centerOnNode, centerNodeId, loading])

  return (
    <div className="h-full w-full">
      {loading && <Loading />}
      <ReactFlow
        proOptions={proOptions}
        className="z-0"
        onPaneClick={() => {
          setSelectedStepId(undefined)
        }}
        nodeTypes={nodeTypes}
        // Nodes are the steps
        nodes={layoutedNodes}
        // Edges connect the nodes together
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        defaultViewport={defaultViewport}
        minZoom={0.1}
        maxZoom={1.5}
        zoomOnScroll={false}
        panOnScroll={true}
        nodesConnectable={true}
        zoomOnDoubleClick={false}
        nodesDraggable={true}
        deleteKeyCode={null}
      >
        <Background />
        <Controls showInteractive={false} />
      </ReactFlow>
    </div>
  )
}

// as we are accessing the internal React Flow state in our component, we need to wrap it with the ReactFlowProvider
const ReactFlowWrapper = () => {
  const { selectedStepId, setSelectedStepId } = useContext(
    WorkflowBuilderContext
  )

  return (
    <div className="flex h-full flex-row overflow-y-auto">
      <Flow />
      <StepDetailsAside
        active={selectedStepId !== undefined}
        onClose={() => {
          setSelectedStepId(undefined)
        }}
      />
    </div>
  )
}

export default ReactFlowWrapper


Can't see connection line creating with drag and drop is disappear after render or refresh page.
