### ISSUE TITLE
Cannot zoom in and zoom out after a particular level

### ISSUE THREAD

**Issue by ShafahJiitak** [wbkd/react-flow#1597]
Cannot zoom in and zoom out after a particular level or percentage

**Comment by moklick** [comment]
you can pass a `minZoom` (default 0.5) and `maxZoom` (default 2) level.

**Comment by thadk** [comment]
Coming from plus and minus buttons on maps (Google, Mapbox, etc) where zoom levels increase as you get more detailed, the meanings of minZoom and maxZoom are inverted for `react-flow-renderer`. It becomes a bit visible when you set `defaultZoom` but this tripped me up for months afterwards because I'm so used to map use cases. 

You might add a bit of a reminder what each means in the docs. `maxZoom` is actually the most fine zooming you can do, `minZoom` is for a global view.
