### ISSUE TITLE
[Example breaking] Unable to save the flow

### ISSUE THREAD

**Issue by piyushchauhan** [wbkd/react-flow#1717]
When I trying to click on the save and restore buttons on this webpage https://reactflow.dev/examples/save-and-restore/
I am not able to see the object being logged into the console.

Also I tried using the example as given here https://github.com/wbkd/react-flow/tree/main/example/src/SaveRestore

I am getting the following error.
```
localforage.js:1053 Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': Symbol(react.element) could not be cloned.
    at http://localhost:3000/static/js/vendors~main.chunk.js:43466:33
    at createTransaction (http://localhost:3000/static/js/vendors~main.chunk.js:43219:11)
    at http://localhost:3000/static/js/vendors~main.chunk.js:43451:13
```

This is the line that is throwing the error `var req = store.put(value, key);`

**Comment by xplato** [comment]
I'm not sure about issue 2 with that error message, but the objects in this example aren't logged to the console; they are placed in the IndexedDB (at least within my browser).

**Comment by piyushchauhan** [comment]
Does refreshing the page destroy that saved object?

I followed these steps on the example page.

1. Load the page. The nodes appeared one below another.
2. moved few nodes here and there.
3. Refreshed the page

The nodes again appeared one below another as it should since I didnot hit save.

Then

1. Load the page. The nodes appeared one below another.
2. moved few nodes here and there.
3. Hit save
4. Refreshed the page

The nodes again appeared one below another as it should since I didnot hit save.

**Comment by xplato** [comment]
Click "Save" to save the current state via the `localforage` package. This, as we've determined, uses the IndexedDB API (most likely). This will save those changes there which **will persist** across reloads.

The reason you're not seeing the saved data when you reload is because of the following line in the example:

```
const [elements, setElements] = useState(initialElements);
```

They are not being populated automatically, by design. This is why there is a "Restore" button. This example does work.

To test:

1. Move a node to the right, for example.
2. Hit "Save"
3. Reload
4. Hit "Restore"
5. You should see that, upon clicking "Restore," the node position is restored back to where you moved it in step 1.

---

This example is merely a demonstration. In a real project, you'd most certainly be automatically populating the elements state with some array that you've saved, in a manner of your choosing. That is, you can use `localforage`, the built-in `localStorage`, or some other method (most commonly, via a server API).

**Comment by moklick** [comment]
The example works as expected. You can add nodes, click save, refresh the page and then click restore to load the saved state.

**Comment by TheJustExper** [comment]
This is still happening, I also get this error when trying to save the Object to localforage

**Comment by gryslik** [comment]
I am getting exactly the same error.
