### ISSUE TITLE
[Urgent] React Flow seems to be destroying design system styling

### ISSUE THREAD

**Issue by piyushchauhan** [wbkd/react-flow#1718]
I was trying to use ant design with react flow. React flow is not allowing me to render the sytling of andt components like for save workflow button is primary but it seems to be plain.
![image](https://user-images.githubusercontent.com/5148334/143735414-6f47375c-c99d-4798-8851-b37266447185.png)

**Comment by piyushchauhan** [comment]
@moklick How do I use my design system react components with react flow?

**Comment by xplato** [comment]
Are you referring to the `ul` in the top-left? ReactFlow, as far as I'm aware, prefixes all (or most, at least) classnames with `.react-flow`, which should prevent any and all style collisions.

Because of this, I think there's an error within your project that is unrelated to ReactFlow. Have you verified that your stylesheets are being properly loading on this window you've pictured?

If you're quite sure this is related to ReactFlow, create a reproducible Codesandbox to allow me to investigate this issue. Best of luck.

**Comment by moklick** [comment]
This is not an issue with React Flow. We are using it with style systems too. As @xplato pointed out all classes are prefixed and there should be no interference with other styles.
