### ISSUE TITLE
Custom labels with foreignObject elements disrupt pan click and dragging

### ISSUE THREAD

**Issue by JonNode28** [wbkd/react-flow#1906]
### Describe the Bug

Custom labels with foreignObject elements disrupt pan click and dragging.

I've confirmed that this still applies in `10.0.0-next.39`

### Your Example Website or App

https://reactflow.dev/examples/edge-with-button

### Steps to Reproduce the Bug or Issue

1. Go to `https://reactflow.dev/examples/edge-with-button`
2. Try and pan by starting the drag just to the bottom right of an edge button

### Expected behavior

The canvas should pan

### Platform

- OS: macos
- Browser: Firefox and Chrome
- Version: ^9 and ^10

### Additional context

This becomes more of a problem for labels that can be of a variable size

**Comment by JonNode28** [comment]
I wonder if edge labels would be better off being managed outside the svg, similar to nodes

**Comment by moklick** [comment]
This is a special case and I am not sure if I would call it an issue. I agree that it would be nice if we could just use divs and have an separate renderer for the labels but this is another point. In this example we have a round button and we can only have rectangle shaped parent foreignObjects. That's why you can't drag in the corners of the button. You could improve it by reducing the size of the foreignObject so that is has the same size as the button (in the example it's just too big). When edge labels have pointer-events=none or have a rectangle shape, this isn't an issue at all.

**Comment by JonNode28** [comment]
The example uses a label with a fixed height and width so yes, in this case we can reduce the size of the foreignObject and the issue is virtually non-existent. 

But if you're using foreignObject then you're likely trying to create an edge label that is rich and variable in size. As I was.

It's possible to listen to changes in the size of the content of the foreignObject and alter it's dimensions so that it wraps it closesly but it's messy and so far quite unreliable, hence why I opened this issue.

This does feel like a design issue. The library currently doesn't support feature rich edge labels IMO.

**Comment by moklick** [comment]
I added a div based renderer for edge labels in v11.2.0. Could you check, if that fixes this issue? https://reactflow.dev/docs/api/edges/edge-label-renderer/

**Comment by moklick** [comment]
Please re-open if this issue still persists.
