### ISSUE TITLE
Very poor user experience on touchscreens

### ISSUE THREAD

**Issue by Immortalin** [wbkd/react-flow#1935]
### Describe the Bug

User experience on touchscreens is very bad, especially compared to alternative libraries like Rete.js.
- Edge connection does not work, edge connector hit box is very small
- Edge connection dragging and updating does not work well, the rest of the frame tend fo pan/scroll when attempting to update node edge on iPad
- Drag and drop example requires long press and hold to activate drag functionality on touchscreens
- Drag and drop example pages scrolls too much and doesn’t reliable trigger drag and drop

### Your Example Website or App

https://reactflow.dev/examples/updatable-edge/

https://reactflow.dev/examples/drag-and-drop/

### Steps to Reproduce the Bug or Issue

N/A

Tested with the examples on the official documentation website

### Expected behavior

Edge connections should be able to easily connect and disconnect on mobile. Edge connector should have a larger hit box for fingers. See:
https://rete.js.org/#/examples/basic

Drag and drop UX needs to be more responsive and sensitive, page shouldn’t scroll when attempting to drag on touchscreens. A better implementation:
https://shopify.github.io/draggable/examples/simple-list.html

### Platform

Tested on iOS 15, Safari/WebKit

### Additional context

Retejs has excellent touchscreen support for the edge connections, just copy what they are doing. For drag and drop, the behaviour needs to be revamped, it is very awkward to use right now on touchscreen.

**Comment by leejustin** [comment]
Mobile is available in the next release: https://github.com/wbkd/react-flow/discussions/1677#discussioncomment-1833493

**Comment by moklick** [comment]
Hey @Immortalin 

In v9 there is no support for touch devices at all.

To your points:

* Edge connection does not work, edge connector hit box is very small - **this is fixed in v10 and the edge connector hit box is adjustable via css**
* Edge connection dragging and updating does not work well, the rest of the frame tend fo pan/scroll when attempting to update node edge on iPad - **there is currently no support for this specific feature for touch devices**
* Drag and drop example requires long press and hold to activate drag functionality on touchscreens - **this has nothing to do with React Flow. It's a simple example that uses the native HTML5 drag and drop API. Of course you can use a library that does a better job in your application**
* Drag and drop example pages scrolls too much and doesn’t reliable trigger drag and drop - see above

**Comment by Immortalin** [comment]
Are there any plans to add support for updating edge connections on touchscreens?

**Comment by wulinsheng123** [comment]
> * Edge connection

me too , I met same problem.
