### ISSUE TITLE
onDragStop always triggle onClick in custom node component.

### ISSUE THREAD

**Issue by Holybasil** [wbkd/react-flow#1975]
### Describe the Bug

```js

// index.js
const nodeTyps = {
  custom: CustomNode
}
<ReactFlow nodesDraggable />


// CustomNode.js

// handleCustomClick always trigger by onDragStop
<div onClick={handleCustomClick}></div>
 
```
### Your Example Website or App

https://codesandbox.io/s/react-flow-drag-jled0w

### Steps to Reproduce the Bug or Issue

1. drag the node 2
2. see "node click" in console below

### Expected behavior

onNodeDragStop not trigger onClick.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

It works but I don't know if there are side effects

```js
// src/components/Nodes/wrapNode.tsx
...
setTimeout(() => {
      updateNodePosition({
            id,
            dragging: false,
      });
}, 300);
...
```

**Comment by Holybasil** [comment]
by the way,  [Codesandbox Example](https://codesandbox.io/s/react-flow-starter-ou8or) in **bug report** is v9 and it needs to upgrade to v10

**Comment by Sec-ant** [comment]
I think this is the intended bahaviour and it has nothing to do with `onNodeDragStop`. Because if you drag your node around, you'll have to trigger a `mouse down` - `mouse up` action, which is a `click`.

**Comment by markwatabe** [comment]
related but slightly different:

1. onDragStart fires on mousedown, even with no movement
2. onDragStop only fires if there has been movement

That makes it hard to use those two seamlessly if I want to do something differently while dragging, because I cannot rely on stop firing reliably. If I have to check for my movement after onDragStart, it kind of defeats the purpose of that event doesn't it?
