### ISSUE TITLE
Stability of nodes and edges levels

### ISSUE THREAD

**Issue by Sec-ant** [wbkd/react-flow#1977]
### Describe the Bug

A node can be displayed at the max `z-index` level when selected, but when it is deselected, its level will be reset to the initial level (which is defined by the render order I think). Therefore, a user cannot rearrange the level order of the nodes. This behavior is a little unconventional and may cause some problems in applications.

### Your Example Website or App

https://reactflow.dev/docs/examples/overview/

### Steps to Reproduce the Bug or Issue

1. Drag one of the upper nodes over some of the lower nodes. The upper node will cover the lower ones.
2. Click the blanket to deselect the upper node.
3. The upper node is covered by the lower ones.

### Expected behavior

The levels of the nodes shouldn't be affected by deselection.

### Screenshots or Videos

https://user-images.githubusercontent.com/10386119/158810010-91d4d5d4-1406-45ac-9728-8ee819b2d7c4.mp4

### Platform

- OS: [Windows]
- Browser: [Edge]
- Version: [v10]

**Comment by Sec-ant** [comment]
A possible fix is apart from re-assigning the new z-index level when selecting the node, we also move the node to the end of the children array.

**Comment by AustinGilliam** [comment]
Just wanted to chime in that something similar seems to be happening with edges. Selecting a node rises the z-index of all the edges attached to it, so that it displays over other nodes. You can see it in the Overview example referenced above, but not in the [Overview Example in the v9 docs](https://v9.reactflow.dev/examples/).

In my own application I specifically set the z-index of the edges, so them being changed in this way causes some weird behavior.

**Comment by Sec-ant** [comment]
@AustinGilliam Hi, do you mean that you do not want the edges to be risen up by selecting the nodes? I personally like this behavior. And I believe this is introduced because of the [sub flows](https://github.com/wbkd/react-flow/pull/1555#:~:text=Edges%20in%20Subflows%20or%20between%20different%20levels) feature. The levels of edges are determined by their connected nodes, so if the problem stated in this issue is resolved, I believe all the edges will be good too. Actually there's a another problem due to the introduction of `z-index` into edges, for which I opened an issue here: https://github.com/wbkd/react-flow/issues/1966

**Comment by AustinGilliam** [comment]
> @AustinGilliam Hi, do you mean that you do not want the edges to be risen up by selecting the nodes? I personally like this behavior. And I believe this is introduced because of the [sub flows](https://github.com/wbkd/react-flow/pull/1555#:~:text=Edges%20in%20Subflows%20or%20between%20different%20levels) feature. The levels of edges are determined by their connected nodes, so if the problem stated in this issue is resolved, I believe all the edges will be good too. Actually there's a another problem caused by the introduction of `z-index` into edges, for which I opened an issue here: #1966

I personally don't like it if you're using edge labels, because you can drag a node such that the label of its edge completely occludes another node label beneath it. Github seems to be having some issues, as I can't currently upload a screenshot. But you can replicate in the Overview Example by dragging "This is a default node" such that the edge label occludes "Node id: 5". This also causes issues with custom nodes that have "badges" attached to them, e.g. some architecture styles have visual elements that extend beyond the border of the base node (see [ArchiMate's ApplicationComponent](https://pubs.opengroup.org/architecture/archimate3-doc/chap09.html#:~:text=Figure%2072%3A-,Application,-Component%20Notation)). In this case, the edge will show above the badge, which isn't functionally breaking anything, but is not visually pleasing.

However, I get the rationale from a grouping perspective, so it's tricky. I would expect that if I had Group Node A with children Nodes B and C, and an Edge E between B-C, that the z-index of E would be higher than A. Maybe it could be a togglable option? I understand that the use case I described above is a probably a little niche, so I'd be happy to manually set the z-index in my case.

**Comment by Sec-ant** [comment]
@AustinGilliam Thanks for the explanation, you've mentioned some fair points, and I think this can be discussed further so I just changed the issue title.

I can list some design options here:

### levels of nodes
1. Keep nodes levels unchanged, even if they get selected
   Just like Simulink, where the order of the levels can only be adjusted manually from the menu bar.
2. Keep nodes levels unchanged, but move to a higher level when the nodes are selected and move back to their initial level when they are deselected
   The current design in react-flow, in both v9 and v10. The levels of the nodes cannot be changed (deselecting will put everything to their initial levels).
3. Move to a higher level when the nodes are selected, and keep their levels when they are deselected
   My personally expected behavior and thus this issue.

### levels of edges
4. Keep edges levels unchanged, even if their connected nodes are selected
   v9
5. Keep edges levels unchanged, but move to a higher level when their connected nodes are selected, and move back to their initial level when the nodes are deselected.
   v10
6. Move to a higher level when their connected nodes are selected, and keep their levels when they are deselected

When there are labels or foreign objects on the edges instead of just plain line shapes, the selecting or deselecting of edges themselves can also bring up some more options to be considered.

I personally prefer 3 and 5, but this is way more complex than I thought, because we have to take sub flows and a lot of other things into consideration. Maybe a togglable option is what we need in the end.

I'd love to hear all your thoughts~

**Comment by ERuseckas** [comment]
One more issue related to edge levels:

User can not select edge, which is rendered inside sub flow.

**Comment by AustinGilliam** [comment]
@Sec-ant I would say in general I think option 2 or 3 and 5 are a good implementation, as I think a lot of users that just want React Flow to look nice out of the box would expect that. However, and to your point, I would like to be able to turn it off (at least for edges, i.e. get back option 4), and manage the z-index by myself — especially for more complex use cases.

**Comment by chrtze** [comment]
Thanks for your thoughts on the updated zIndex logic. We have designed the default behavior of the nodes and edges in React Flow v10 like this:

* nodes are being rendered above the edges according to their order in the nodes array
* edges are being rendered behind the nodes according to their order in the edges array
* edges inherit the zIndex of their source or target with the highest zIndex (default will be 0)
* once a node is selected or dragged, it gets zIndex 1000 (we should probably make this value configurable in the future) to lift the node and their connected edges above everything else

This behavior can be customized:

* to control the initial stacking order, simply change the order of the nodes and edges in their arrays
* to disable the elevation of nodes on select/drag, you can apply a zIndex option to the nodes, this value will take precedence over the default value (1000)
* to disable the elevation of edges on node select/drag, you can apply a zIndex option to the edges or set `defaultEdgeOptions={{ zIndex: 0 }}`

I agree that this seems to be too complicated, if you want to have the v9 behavior out of the box. Maybe we can add a property that allows to control this behavior, but for now I think the easiest way is to use `defaultEdgeOptions={{ zIndex: 0 }}`.

**Comment by sudarsanarao995** [comment]
> One more issue related to edge levels:
> 
> User can not select edge, which is rendered inside sub flow.

yes , I increased z-index value 1  in react_flow_edges, then able to select the edge but issue getting edges are getting above the nodes
