### ISSUE TITLE
Nodes multi selection doesn't work with selectNodesOnDrag disabled

### ISSUE THREAD

**Issue by alessandropisu** [wbkd/react-flow#1985]
### Describe the Bug

I notice that nodes multi selection doesn't work when selectNodesOnDrag  is false, both in Controlled and Uncontrolled mode. It doesn't seems to be the right behavior as is doing a different functionality compared to nodes selection on drag.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-3l48jx?file=/App.js

### Steps to Reproduce the Bug or Issue

Select a node, then click a second node with Meta/Command pressed

### Expected behavior

All nodes should be selected and not only the last one

### Platform

- OS: macOS
- Browser: Chrome
- Version: v10

**Comment by Sec-ant** [comment]
I can confirm this has something to do with this line of code: https://github.com/wbkd/react-flow/blob/3548891b8e4f6ffbb9de1fbbef582d8eb55304c7/src/components/Nodes/wrapNode.tsx#L115

If you comment it out, you'll be able to multiselect nodes. However the logic here is too complicated to be simply disable this because this function guarantees when you drag another node, the previous selected nodes will be deselected.

**Comment by Sec-ant** [comment]
I made a PR to fix this issue: https://github.com/wbkd/react-flow/pull/1988
