### ISSUE TITLE
setEdges([]) doesn't work - setting empty edges array cannot be empty.

### ISSUE THREAD

**Issue by shemeshx** [wbkd/react-flow#2117]
### Describe the Bug

When I try to set empty edges array it doesn't work and it still shows the previous edges.
I attached an example with the sandbox

### Your Example Website or App

https://codesandbox.io/s/sweet-drake-201b6e

### Steps to Reproduce the Bug or Issue

1. click on the remove edge buttons. 
2. you can see in the console that all the edges still exists but suppose to be empty.

### Expected behavior

As user I suppose to click on the clear button and should not see any edge exist but I see all the edges instead.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 100.0.4896.127

**Comment by chrtze** [comment]
Hi @shemeshx, I think you are mixing controlled and uncontrolled behaviour of React Flow. You can only use `setEdges` when you are not handling the state yourself (for example by passing `defaultEdges` instead of `edges` property to React Flow). Working example based on your codesandbox: https://codesandbox.io/s/sleepy-night-uqjgi6

You might want to use `setEdges` from your own state rather than importing it from `useReactFlow`.
