### ISSUE TITLE
Bug: Dynamically adding Nodes creates errors in state

### ISSUE THREAD

**Issue by mohannva** [wbkd/react-flow#2151]
### Describe the Bug

When adding a node dynamically using the "useNodesState" hook, a state error occurs

### Your Example Website or App

https://codesandbox.io/s/musing-mendeleev-dvwbsm

### Steps to Reproduce the Bug or Issue

1. Click on the custom control button to create node
2.  Click into react flow renderer

### Expected behavior

Expect to see a new node appear on the screen with given parameters

### Platform

- OS: Windows
- Browser: Chrome

**Comment by bcakmakoglu** [comment]
Doesn't seem to be a bug tbh but rather that you didn't use `setNodes` correctly.
[Here is a corrected sandbox](https://codesandbox.io/s/crazy-colden-uhsn9v?file=/src/App.js)

The issue is this - you have a top-level variable called `nodes` that you get from 
```ts
  const [nodes, setNodes, onNodesChange] = useNodesState(initialElements);
```

but then you create another variable called `nodes` as the `setNodes` parameter, i.e.
```ts
const addNode = useCallback(()=>{
      setNodes((nodes) => {
        nodes = [...nodes, {
            id: Math.random(),
            type: "input",
            position: {x: 20, y: 10},
            data:{ label: "yo"}
        }]})}
 ,[])
```

this alone should cause a naming collision.

But that's not the whole issue.
`setNodes` expects you to __return__ the array of new nodes, not try to overwrite the `nodes` variable.

So the correct usage would be
```ts
  const addNode = useCallback(() => {
     // use a different variable name for setNodes parameter to avoid naming collisions with the nodes variable from above
    setNodes((n) => {
      // actually return the new array 
      return [
        ...n,
        {
          id: Math.random(),
          type: "input",
          position: { x: 20, y: 10 },
          data: { label: "yo" }
        }
      ];
    });
  }, [setNodes]);
```

When corrected your example seems to work fine 😄

**Comment by mohannva** [comment]
Ah perfect; thanks for catching! I definitely did not realize you had to return the updated array, instead of simply pushing the updated value!
