### ISSUE TITLE
Typescript error for <Handle> prop

### ISSUE THREAD

**Issue by jeremypeters** [wbkd/react-flow#224]
I'm using `<Handle>` within a custom node component and I get the following Typescript error:

`TS2322: Type '"top"' is not assignable to type 'Position'.`

Using 1.3.5

**Comment by moklick** [comment]
Hey,

can you try to import the `Position` type and then do:

```javascript 
<Handle 
  position={Position.Top}
/>
```

**Comment by andys8** [comment]
I ran into the same issue. I believe the [fix](https://github.com/wbkd/react-flow/commit/34188549f3a245a50372d6ae3be13e0263fb1fba) should work. Thanks.

**Comment by jeremypeters** [comment]
Hi @moklick 

I updated to 1.3.7 and I'm getting a couple more errors using your fix:

`Module '"../../../node_modules/react-flow-renderer/dist"' has no exported member 'Position'. Did you mean to use 'import Position from "../../../node_modules/react-flow-renderer/dist"' instead?ts(2614)`

` TS2322: Type '{ type: "target"; position: Position.Top; className: string; }' is not assignable to type 'IntrinsicAttributes & HandleProps'.
    Property 'className' does not exist on type 'IntrinsicAttributes & HandleProps'.`

**Comment by moklick** [comment]
hey @jeremypeters,

I set up a codesandbox with example ts code:

https://codesandbox.io/s/react-flow-customnode-ts-lu18j?file=/src/Flow.tsx

`className` is not a prop type of the `Handle` component and `Position` gets exported since the last version. Does the code example help you to solve this or is there still an issue with the library?

**Comment by moklick** [comment]
Hey
