### ISSUE TITLE
Default delete key handler preventing users from using backspace in other elements on the page

### ISSUE THREAD

**Issue by EzraBrooks** [wbkd/react-flow#2254]
### Describe the Bug

When the `ReactFlow` component is present on a page, the backspace key is intercepted and seems to be prevented from working anywhere else on the page (other than purely native text inputs completely controlled by the browser).

I don't think that document-scope key event handlers should be calling `Event.preventDefault()`.

### Your Example Website or App

https://codesandbox.io/s/sharp-tharp-jhxqm4?file=/src/App.js

### Steps to Reproduce the Bug or Issue

1. See above example
2. Attempt to backspace text out of the text input (it doesn't work)
3. Set `deleteKeyCode={null}` in the Flow component
4. Note that using backspace in the text input now works

### Expected behavior

As a user, I should be able to use the backspace key elsewhere in the window.

### Platform

- OS: macOS
- Browser: Chrome, Safari
- Version: 103.0, 15.5

### Additional context

The example I provided is using exactly the UI component library that I am using, for maximum accuracy to my use case.

**Comment by chrtze** [comment]
Hi @EzraBrooks, thanks for your issue.

The problem here is that the library you are using is rendering a custom web component (rux-input) and not a standard input field. When you are using a normal input field or another library that just renders an input field, everything works fine. In our keyboard handler, we are checking if you are in an input field or in a textarea, and don't handle the event if that's the case.

However, you can workaround this issue with the library you are using by preventing react flow from receiving the keydown event. You can find a working example here: https://codesandbox.io/s/youthful-bartik-on37r9?file=/src/App.js

**Comment by EzraBrooks** [comment]
It's been a while since I last did this, so I may be misremembering, but aren't you able to add focus capability to any element by giving it a tab index?

**Comment by chrtze** [comment]
yes, but I am not sure if that is what we want (would this mean you need to press tab first before you can delete the elements?). when I think about it, the current behavior makes sense in full screen apps but not so much if you have multiple flows on one page. maybe we can find an example for what the best ux would be here. i'll reopen the issue for now.

**Comment by chrtze** [comment]
In the next major version (v11) you can add a class name `nokey` to all elements that should be treated as an input field.

**Comment by kahboom** [comment]
@EzraBrooks - I've been stuck on this issue for several days and couldn't quite figure it out. Actually in my case it was even causing a complete re-render at times when pressing the backspace. Your workaround fixes it, thanks so much!

**Comment by BrianHung** [comment]
@moklick Can `nokey` be documented in https://reactflow.dev/docs/? Thanks
