### ISSUE TITLE
Auto Layouting is not working using Dagree Tree

### ISSUE THREAD

**Issue by jayanthbondi** [wbkd/react-flow#2323]
### Describe the Bug

I'm trying to add a Dynamic Node to the already existing layout on click of "Add Dynamic Node" button.
But it's not working as expected.

Could you please let me know where am I making the mistake.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-r7wg2v?file=/App.js

### Steps to Reproduce the Bug or Issue

Click on "Add Dynamic Node" button.

### Expected behavior

As a user , I'm expecting a new Node 2e would be added and connection would be established between 2 & 2e.
But I'm not seeing the 2e Node.

### Platform

- OS: [ Windows]
- Browser: [Chrome]

**Comment by mpolichette** [comment]
Your `_setNodes` is updating react state for `_nodes`, this becomes a parameter for the layout algo, but ultimately ends up as **only the initial state** for `useNodesState`...  

Since it is only the initial state, it doesn't actually update the state.  At some point you need to us the returned `setNodes` from `useNodesState` to update the rendered nodes.

Same idea goes for edges.
