### ISSUE TITLE
Custom Nodes are not getting a connection line between them when a new node is created

### ISSUE THREAD

**Issue by kash0296** [wbkd/react-flow#2496]
### Describe the Bug

I have created Custom Nodes for my company's  usecase. Our goal is to build a workflow builder. However, we felt the example provided was not exactly what we had in mind, so I set up our flow diagram based off the [Add Node on Edge Drop](https://reactflow.dev/docs/examples/nodes/add-node-on-edge-drop/) example.

So far for the most part, things are working fine, but I have a couple of issues that I wish to raise, with the most important one being the fact that when I create a new node, the handles of the source and target node are not connected. I get the following warning message:

[React Flow]: Couldn't create edge for source handle id: 0-source-handle}; edge id: 0 => 1.

There was a link attached which explains the error, and I did take a look at it, but I'm not sure what is wrong with the logic in my sandbox.

Here's how my flow diagram looks on the sandbox:
![image](https://user-images.githubusercontent.com/70874363/195764570-1c8d782c-1ef3-4407-bc9f-03eebe9371f5.png)

Additionally, I have the following question:

How do I reduce the zoom of the flow diagram by default?  The default zoom feels quite zoomed in. I tried using the defaultViewport property like this:

`const defaultViewPortOptions = {
  x: 0,
  y: -300,
  zoom: 0.25
};`

However, this does not change the zoom. Specifying min and max zoom values to the fitViewOptions object however changes it for me. What is the purpose of the defaultViewport property then? Could you clarify this for me please?

I would also like to know what property I have to specify so that my Start Node by default is positioned higher up the screen. I know i can do this by setting the position value in the initialNodes property for this node, but isn't it possible to do it with defaultViewport?

### Your Example Website or App

https://codesandbox.io/s/exciting-sky-xxq3z4

### Steps to Reproduce the Bug or Issue

1. Go to my sandbox
2. On the UI screen, there is a default node called Start. Click on the plus icon
3. It creates a new node, but the two nodes do not get connected, but I instead get a warning : [React Flow]: Couldn't create edge for source handle id: 0-source-handle}; edge id: 0 => 1.

### Expected behavior

I expected that my Custom Nodes would be connected, but they are not.

### Platform

- OS: Linux (Ubuntu 20.04
- Browser: Google Chrome
- Version: 105.0.5195.125

**Comment by kash0296** [comment]
I forgot to mention this but I am using the latest version of Reactflow v11.

**Comment by chrtze** [comment]
Hi @kash0296, please see my codesandbox with edits: https://codesandbox.io/s/nice-violet-fpyimh?file=/src/App.js

1. The reason why the edge could not be drawn by React Flow was that the source and target handles where not rendered when your custom node was not connected (https://codesandbox.io/s/exciting-sky-xxq3z4?file=/src/CustomNodes/StarterNode.jsx:231-267), so the connection could not be made. I have removed the condition to render the handles so that they are rendered all the time. I am assuming you want to hide the handles as long as the node is not connected. Therefore, I would recommend to do this via CSS, for example: `style={{ opacity: data.isConnected ? 1 : 0 }}`.
2. The `defaultViewPort` did not have any effect because you are setting the `fitView` prop. The `fitView` prop tells React Flow to center all elements in the viewport on load. To have more control on the initial view, you can remove the `fitView` prop and pass your configuration with `defaultViewPort` (see my sandbox as example). Also notice that you might want to set `minZoom` and `maxZoom` as this limits the zoom by default.
3. For displaying the nodes more up the screen, I would recommend adjusting the `defaultViewPort` prop instead of moving the nodes with their position individually.

Hope that helps!

**Comment by kash0296** [comment]
@chrtze Thank you for a quick response! I really appreciate the help. This works for me. Should I face any further issues with anything else, I will post on the issues thread if I don't already find a solution from other posts.

Thanks again!
