### ISSUE TITLE
Add more styling option to the mini map 

### ISSUE THREAD

**Issue by rickixie** [wbkd/react-flow#2550]
### Please describe the feature that you want to propose

Hi, we are using the mni-map in our diagram and would like to have more styling option
1. Ability to add an border to the inner mask (so that it is more clear where the zoom area is)
2. Able to add a drop-shadow and border radius to the mini-map so that is is apparent that it is floating on top of the canvas.

This is what we were thinking of  :) -- 
![image](https://user-images.githubusercontent.com/5816630/200675434-b2f78b85-16d4-4083-892c-388e280d4f47.png)

**Comment by chrtze** [comment]
Hi, the minimap is just a svg and the elements have class names so you could style it with CSS (although there are limitations). Did you try adding a stroke to the inner mask path (`.react-flow__minimap-mask`). The box-shadow and border radius can be applied to the `.react-flow__minimap` element.

**Comment by NicL9923** [comment]
@chrtze Our team found these and tinkered with them enough to get our desired look above, but it felt a little more involved than the more convenient option of just specifying the maskColor prop, so the feature request is more of a convenience ask if anything

It may be unavoidable due to the fact that it is a mask versus something else, but setting the stroke color meant that both the outer and inner edges (the inner being the desired effect of course) were affected, so we had to hack-ily force the mask to be larger and then hide its overflow. If this is just the way it is, then no further issue, but again, it would certainly be a nice convenience to be able to have the viewport outline effect achievable as easily as the maskColor

Either way, thank you for the help!

**Comment by chrtze** [comment]
@NicL9923 I understand. As we are trying to keep React Flow as low level and simple as possible, this would add complexity which is not necessary in my opinion. To make it easier to style the elements, I assume we would need to change the svg rendering to not be a mask but a rectangle or something. I guess this would be more suitable as you would then be able to style everything easily with CSS.

**Comment by moklick** [comment]
we've added `maskStrokeColor` and `maskStrokeWidth` in v11.3.0. The boxShadow can be done by using the style prop.
