### ISSUE TITLE
Custom label utilizing EdgeLabelRender component rendering issue

### ISSUE THREAD

**Issue by liuruenshen** [wbkd/react-flow#2551]
### Describe the Bug

When using the EdgeLabelRender component to render the custom label and there are multiple flows on the page, all the labels get rendered into one flow that doesn't belong to those labels.

### Your Example Website or App

https://codesandbox.io/s/jolly-tree-rox457

### Steps to Reproduce the Bug or Issue

1. See the example above.

### Expected behavior

The labels should be rendered inside its own flow.

### Platform

- OS: macOS
- Browser: Chrome/Firefox
- Version: 11.2.0

### Additional context

The issue can be resolved by this PR: [2547](https://github.com/wbkd/react-flow/pull/2547)

**Comment by chrtze** [comment]
Hi @liuruenshen, thanks for raising this issue. I think it's a bug. We are using `getElementById` to [find the portal](https://github.com/wbkd/react-flow/blob/main/packages/core/src/components/EdgeLabelRenderer/index.tsx#L6) for the labels. This will always return the DOM element of the first flow on the page instead of the portal div that belongs to that flow. I will have a look into this.

**Comment by liuruenshen** [comment]
Hi @chrtze, thanks for investigating the issue; maybe you can consider my PR? Let me know if you have any questions or suggestions; thanks.

**Comment by chrtze** [comment]
Sorry, I somehow overlooked it. Thanks for opening the PR. Let's move the conversation there to get this done :)

**Comment by moklick** [comment]
thakns @liuruenshen . This is fixed in v11.3.0
