### ISSUE TITLE
`getMarkerEnd` returning an incorrect id

### ISSUE THREAD

**Issue by martin-dimi** [wbkd/react-flow#2584]
### Describe the Bug

Hey, I've started to use `getMarkerEnd` to get a closed arrowhead marker to use within my custom edge. It seems the returned string is unrecognised as no marker end is rendered. 

```
// ... CustomEdge.tsx
      <path
        id={id}
        style={style}
        className="stroke-gray-400"
        d={edgePath}
        markerEnd={getMarkerEnd(MarkerType.ArrowClosed)}
      />
```

Further, if I provide the `markerEnd` through the edge structure, e.g.
```
const edge = {
        id: someId,
        source: node.id,
        target: destination,
        type: edgeType,
        markerEnd: { type: MarkerType.ArrowClosed },
}
```

I noticed there's a slight difference in the strings:
* `url(#1__type=arrowclosed)` <- passed down from edge structure
* `url(#react-flow__arrowclosed)` <- retrieved from `getMarkerEnd`

### Steps to Reproduce the Bug or Issue

1. Define a custom edge
2. Use `getMarkerEnd` to retrieve closedArrowhead for path's markerEnd
3. No Arrow head is rendered on edge as the url id is invalidArrowhead

### Expected behavior

I expect to see an arrowhead being rendered on the edge.  There's a mismatch between markerEnd strings:
* `url(#1__type=arrowclosed)` <- passed down from edge structure
* `url(#react-flow__arrowclosed)` <- retrieved from `getMarkerEnd`

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Reactflow Version: [11.3.0]

**Comment by bcakmakoglu** [comment]
I hope I didn't misunderstand you but here are my thoughts:

So, for markers to work, you *need* to define them in your edges, otherwise there will be no marker definitions you can reference via `url()`.

Meaning, what you describe as "providing through edge structure" is required for the marker to appear.

Furthermore, when you have defined a marker and want to use it in a custom edge, the url is already provided to your custom edge as a prop so using `getMarkerEnd` is superfluous.
[Check this example and open the `CustomEdge.js` file](https://reactflow.dev/docs/examples/edges/custom-edge/), you can see that there is no `getMarkerEnd` call, you just pass the `markerEnd` prop to your path and that's it.

**Comment by moklick** [comment]
thanks @bcakmakoglu 🙏

**Comment by martin-dimi** [comment]
Yes, you're correct! 
Thanks!
