### ISSUE TITLE
`reactFlowInstance.setNodes` is not updating all nodes on the graph

### ISSUE THREAD

**Issue by cliffordfajardo** [wbkd/react-flow#2637]
### Describe the Bug
When I call `reactFlowInstance.setNodes`, it does not update re-render all my custom node elements.

https://user-images.githubusercontent.com/6743796/205755496-659af73d-bc7f-4f54-a4cd-56d0760c6ee1.mp4

### Background Context
In my app, I need to use Custom nodes and edges to build a very particular/customized UI, so I can't use the default nodes

### Your Example Website or App
Codesandbox: https://codesandbox.io/s/bug-react-flow-not-re-rendering-custom-nodes-cqhoon?file=/app/components/ReactFlowHookExample/CustomNode.tsx

### Steps to Reproduce the Bug or Issue

1. Hover over my CustomNode element (all of them are custom nodes in the graph)
2. Upon hover `highlightNodesandEdgesConnectedToMe` will get called, which updates the nodes by adding an object inside of `data` property called `customCSSStyles`:

```ts
// onMouseEnter
const updatedNodes = [...].map(node =>) {
  if(shouldHighlight) node.data.customCSSStyles = {...HIGHLIGHTED_NODE_STYLES}
  return node
}
reactFlowInstance.setNodes(updatedNodes) // does not trigger a re-render of my graph
```

### Expected behavior
When I call `reactFlowInstance.setNodes`, it should trigger a re-render of the nodes elements that changed in the graph

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 11.3.2

**Comment by chrtze** [comment]
Hi @cliffordfajardo, I somehow can't fork the sandbox (maybe due to the build settings). Could you try changing this line: https://codesandbox.io/s/bug-react-flow-not-re-rendering-custom-nodes-cqhoon?file=/app/components/ReactFlowHookExample/CustomNode.tsx:1632-1699 to:

```jsx
node.data = {
  ...node.data,
  customCSSStyles:{   
    ...HIGHLIGHTED_NODE_STYLES
  },
}
```


Internally, React Flow doesn't check if a nested object has changed, it will only trigger an update if  node.data changes, not if node.data.customCSSStyles changes.

Let me know if that works for you.

**Comment by cliffordfajardo** [comment]
Yes, closing was able to resolve ✔️
