### ISSUE TITLE
Zooming / panning is causing nodes to re-render for no reason

### ISSUE THREAD

**Issue by bartvanremortele** [wbkd/react-flow#282]
If you zoom and pan the nodes are being re-rendered which is impacting performance if you have a lot of nodes. 

![Schermafbeelding 2020-06-05 om 12 07 39](https://user-images.githubusercontent.com/424370/83864649-50d53500-a725-11ea-9c32-cfc7de2767c2.png)

**Comment by moklick** [comment]
Hey @bartvanremortele 

I found a little easy-peasy, immer related bug regarding the `updateTransform`action. More over I wrapped the nodes with `memo` and updated the examples. The validation example used inline functions for the isValidConnection prop, that's why it got re-rendered. Maybe you are also creating new functions every time? Do you have an example?

**Comment by bartvanremortele** [comment]
I'll check but I'm not using the isValidConnection prop. It might be because of other props on my custom nodes however. I previously checked if it was still re-rendering when I removed the Handle's from my custom nodes but it still was re-rendering.

**Comment by bartvanremortele** [comment]
I've updated to the latest version and it's already improved quite a bit. Right now I'm still using a style on a custom node with a Handle that's still triggering re-renders but I can work around it.
```
        <Handle
          type="source"
          position={Position.Bottom}
          style={{ background: "rgb(224, 224, 224)" }}
        />
```

**Comment by moklick** [comment]
can you try to do 

```
const style = { background: "rgb(224, 224, 224)" };

const YourComp = () => {
  return (
    <> 
       <Handle
          type="source"
          position={Position.Bottom}
          style={style}
        />
    </>
  );
}
```

When the object is inlined it gets re-created every re-render

**Comment by moklick** [comment]
Hey @bartvanremortele 

can we close this issue or is there still a problem with unnecessary re-renderings?

**Comment by bartvanremortele** [comment]
No, it's fixed. Thanks.

**Comment by Harish-Hk** [comment]
Hey there, I'm facing this issue too.

I'me using many nodes in my project and thats like this.

```
<ConditionalPrompt
            step={step}
            index={index}
            onupdate={this.updateStep}
            getstepnames={this.getStepNames}
            getVariableNames={this.getStepNames}
            addNewParent={this.addNewParent}
            removeParent={this.removeParent}
            filterStepsTobeDeleted={this.filterStepsTobeDeleted}
            ondelete={() => {
              this.deleteStep(step.id, step.parentBranch);
            }}
            onaddafter={(data) => {
              this.openNewStepDrawer(data, index);
            }}
          />
```
any idea what I might be doing wrong?

Thanks in advance

**Comment by moklick** [comment]
Can you show us a code example?

**Comment by joelwkall** [comment]
This is closed since long ago, but I'm also experiencing this issue. I've narrowed it down to my custom nodes usage of 

```
const selector = (s:any) => ({
    nodeInternals: s.nodeInternals,
    edges: s.edges,
});
const { nodeInternals, edges } = useStore(selector);
```

When I remove this, the nodes do not get re-rendered on panning and zooming anymore. Any idea why this causes them to re-render? Is it expected behavior? 

Is there a better way to get a list of edges connected to the node?
