### ISSUE TITLE
Calling fitView() sets view to minimum zoom level

### ISSUE THREAD

**Issue by avin-kavish** [wbkd/react-flow#2999]
### Describe the Bug

I was expecting `fitView()` to use the max possible zoom level that would fit all the contents on screen, but it uses the min zoom level I've set on the component.

### Your Example Website or App

https://codesandbox.io/s/boring-silence-c5rmpy?file=/src/Flow.js

### Steps to Reproduce the Bug or Issue

Just open the codesandbox. There's a `useEffect` hook that runs on mount. It'll trigger the issue.

### Expected behavior

I expect it to use the maximum zoom that would fit the contents. If the component is configured with a minimum zoom level of 0.01 but if 0.8 zoom fits all the contents, it should use that, not 0.01.

### Platform

- OS: Linux
- Browser: Chrome
- Version: latest

**Comment by bcakmakoglu** [comment]
The way I understand `fitView` it's not really using the minimum zoom *unless* the min/max zoom is specified in the options *and* fitting the view would change the zoom level to be below or above min/max values (i.e. it does `clamp(zoom, minZoom, maxZoom)`)

So if you have min/max set to `0.0.1` and `0.8` and got like 4 small nodes on the view, it will automatically zoom because that just the result of fitting the viewport around those nodes.
It has nothing to do with it "automatically" applying the smallest zoom value it can apply.

What you *can* do is enforce a zoom level yourself by passing options to fitView (set min and max zoom to the same value and your zoom won't change at all, the viewport will just be moved so that the nodes are centered).

Your sandbox problem is also a bit different, you're using `padding: 20` which causes the max applicable zoom to be very low. 20 padding is really big, it might not seem that way but try small values like `0.25` and `1` and see the difference it makes.

**Comment by avin-kavish** [comment]
Right. So it looks entirely like a padding issued. Isn't 20 padding supposed to be 20 px? What's the scale based on?

**Comment by bcakmakoglu** [comment]
I don't think the padding scales as `px` values - might be confusing but checking the relevant code it's used like this

```ts
  const xZoom = width / (bounds.width * (1 + padding));
  const yZoom = height / (bounds.height * (1 + padding));
```

So by default this would be width/height * 1.1 (default padding is 0.1)

**Comment by avin-kavish** [comment]
Oh, it's a percentage of the viewport size. I guess the docs could use some clarification, to avoid any confusion  in the future.
