### ISSUE TITLE
Unable to Drag an edge inside a SubFlow

### ISSUE THREAD

**Issue by alikleit-ns** [wbkd/react-flow#3020]
### Describe the Bug

In a subflow that contains connected nodes (either within the subflow node or outside), we're unable to select, nor drag the nodes. This is a problem as a user wont be able to disconnect an existing node within a group after connecting. I tried playing around with the z-index but without any luck. 

I have reproduced it in an existing example from react flow page:

### Your Example Website or App

https://codesandbox.io/s/fervent-danny-sjkhw0?file=/App.js

### Steps to Reproduce the Bug or Issue

1. Add Subflow
2. Add nodes within Subflow
3. Connect the nodes
4. Now, you wont be able to disconnect the edges within the group subflow

### Expected behavior

Ability to select and drag the edges, they should have the same functionality as edges outside the group

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
What you could do to fix the issue for now would be something like this

```css
.react-flow__edges {
	z-index: 9999 !important;
}
```

I realize this is probably not what you want to do but probably the only way to do it at the moment.

@moklick @chrtze 
Wouldn't it make sense to possibly increase the z-index of child nodes by 1?

```ts
      z:
        (parentNode[internalsSymbol]?.z ?? 0) > (result.z ?? 0)
          ? (parentNode[internalsSymbol]?.z ?? 0) + 1 // <-- increase the z index by 1 so children are always layered on top
          : result.z ?? 0,
```

That way the `elevateEdgesOnSelect` prop would also cause edges to be layered on top as well and the issue of OP would be resolved.
Though this would be a sort of side-effect of the prop then and the naming could be slightly confusing as it would push edges to the top even though there was no actual *select* that happened.

But maybe this is intentionally not done, for a reason I'm not aware of, and you guys have another idea how to resolve this 😄

**Comment by moklick** [comment]
Good idea @bcakmakoglu 

For now it should be enough to use a higher zIndex for the edges like this https://codesandbox.io/s/fancy-fire-49um7m?file=/App.js:2087-2102 ?

**Comment by moklick** [comment]
please re-open if the issue persists.

**Comment by egorov-evrone** [comment]
@moklick hey)

The solution mentioned in the issue works. 
However, it has drawbacks. Namely, I'd like to keep edges on the layer behind nodes.
 
I have huge graphs and having edges always seen above nodes somewhat spoils UX.

Could you please tell me if there is any other way to fix this? 

The only thing that comes to my mind is manually updating zIndexes of related to a parent node edges (edge.Zindex += 1000) when a parent node is selected. Didn't find a proper place to do that though.

**Comment by bodinsamuel** [comment]
An imperfect css solution I found: 
```css
/* nodes except groups */
 .react-flow__node:not(.parent) {
  z-index: 20;
}
/* edges */
.react-flow__edges {
   z-index: 10;
}
```

The only issue with that: `.parent` is only defined when a Node contain an actual child. Otherwise it would be perfect.

**Comment by egorov-evrone** [comment]
> An imperfect css solution I found:
> 
> ```css
> /* nodes except groups */
>  .react-flow__node:not(.parent) {
>   z-index: 20;
> }
> /* edges */
> .react-flow__edges {
>    z-index: 10;
> }
> ```
> 
> The only issue with that: `.parent` is only defined when a Node contain an actual child. Otherwise it would be perfect.

Thanks for sharing your solution!

However, at least in my case, it also wouldn't work the way I'd like. 

If one selects a parent node, zIndex of it changes to 1000 and all edges become not dragable/selectable again (because they have zIndex of 10).

The mentioned issue can be solved setting zIndexes to 1001 for regular nodes and edges. That way when a parent node is selected edges still will be above the node.

By the way, zIndexes can also be specified in a node object: https://reactflow.dev/docs/api/nodes/node-options/#zindex-1
To my mind, it's a bit more reliable. That way, we don't rely on the class that could change in the future.

Nevertheless, keeping that change in mind, the approach is still not ideal, unfortunately. If a parent node has some content in it (like a dropdown, or a popover) that opens on click and reaches out of the node boundaries, then it will be behind any other regular node:

![image](https://github.com/wbkd/react-flow/assets/78346995/83cb8937-fd9a-445c-a2d1-b5c7c5f4ab26)

**Comment by nawangwe** [comment]
No fix for this yet? All suggested workaround here amount to new issues with edge rendering.
