### ISSUE TITLE
onNodeDragStop being called on node click

### ISSUE THREAD

**Issue by lucasarleite** [wbkd/react-flow#3028]
### Describe the Bug

I have a callback that should be called only after drag that im passing to onNodeDragStop prop but it is being called when i try to select the nodes as well.

### Your Example Website or App

https://codesandbox.io/s/epic-joliot-q5846b?file=/src/Flow.js:670-684

### Steps to Reproduce the Bug or Issue

1. Left click on any component to select it
2. Check console, both callbacks are being called
3. CMD + left click another component to multiselect
4. Check console again

### Expected behavior

I expected onNodeDragStop to not be called when node is only selected and not dragged 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.137

**Comment by moklick** [comment]
The reason for this is that we don't know if you will start to drag the node when you select it so we need to call `onNodeDragStart` immediately. We then also call `onNodeDragEnd` in order to be able to do any cleanup for example. It would be weird to call `onNodeDragStart` without a `onNodeDragEnd`. You could set a `dragged` flag  in `onNodeDrag` and check that in `onNodeDragEnd` and only call your function when it's true: https://codesandbox.io/s/empty-dew-fjgcxh?file=/src/Flow.js:784-941

**Comment by lucasarleite** [comment]
That makes sense, ty for the response! Im going to try this approach on my side.

**Comment by irfanhathoti** [comment]
@moklick thanks bro

**Comment by moklick** [comment]
We added a new prop called [`nodeDragThreshold`](https://reactflow.dev/docs/api/react-flow-props/#nodedragthreshold) that makes it possible to delay/prevent node drag events. Available since 11.9.0
