### ISSUE TITLE
`PanOnScrollMode.Free` restricted to vertical scrolling with scroll wheel

### ISSUE THREAD

**Issue by rllyy97** [wbkd/react-flow#3099]
### Describe the Bug

When using a mouse with ReactFlow options `panOnScroll={true}` and `panOnScrollMode={PanOnScrollMode.Free}` are set, I would expect the standard `shift+scroll` to horizontally scroll but scrolling remains vertical.

### Steps to Reproduce the Bug or Issue

1. Have new / existing `<ReactFlow />` component
2. Set ReactFlow options `panOnScroll={true}` and `panOnScrollMode={PanOnScrollMode.Free}`
3. `shift+scroll` to try and scroll horizontally
4. ReactFlow canvas will scroll vertically

### Expected behavior

ReactFlow should be able to scroll both horizontally and vertically with the scroll wheel when `PanOnScrollMode.Free` is set.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 11.6.1

**Comment by checkomkar** [comment]
#3272 
#3276 

I have raised a PR addressing this issue. See if this helps. Thanks.

**Comment by bcrudolp** [comment]
OK I did figure this out, but it was odd that this discussion is being held under https://github.com/wbkd/react-flow/ and the fix was in https://github.com/checkomkar/react-flow/ ... is this what's called a "fork" of a repo? (Like I said, I'm new to this and wasn't sure why the fix is implemented in what looked to me like a completely different repo I needed to clone.)

**Comment by checkomkar** [comment]
@bcrudolp yes I have created a copy of this project into my account and raised a PR from there, as I think I cannot directly work on the main repo, even if we could, it's not recommended. 

Even I am new so no worries. We all are learning. :)

Feel free to checkout from my branch and test it out. Thanks.

**Comment by moklick** [comment]
Thanks for the report @rllyy97 - this is fixed in v11.8.1
