### ISSUE TITLE
InteractiveWidth missing pointer-events:all

### ISSUE THREAD

**Issue by oshanley** [wbkd/react-flow#3127]
### Describe the Bug

When creating a custom edge using `BaseEdge`, the property `interactionWidth` is not honored unless you add `pointer-events:all` to the `path` of the non-visible interactive edge. I explained the solution [here](https://github.com/wbkd/react-flow/issues/1211#issuecomment-1585032930).

### Steps to Reproduce the Bug or Issue

Create a custom edge using `BaseEdge` and apply an `interactionWidth` property.  Add a hover state interaction to the desired edge using CSS and observe that it does not occur when hovering in the expected area. Set the CSS property `pointer-events:all` on `g > path:nth-child(2)` and now observe that the functionality works.

### Expected behavior

When creating a custom edge using the `EdgeBase` component and `interactionWidth` property, I expect the interaction width of the edge to increase to the value I set it.

### Screenshots or Videos

https://github.com/wbkd/react-flow/assets/19532793/230c54b9-2740-428a-8be5-01f125830a6b

### Platform

- OS: OS M1
- Browser: Chrome using storybook
- Version:  114.0.5735.106

**Comment by moklick** [comment]
I can't reproduce this. In this example I created a custom edge that uses a BaseEdge with interactionWidth:20 and another one with interactionWidth: 100. Everything works as expected: https://codesandbox.io/s/infallible-ritchie-h9v8vf?file=/App.tsx:920-956

I see that you have a class with pointer-events: border-box. Could this cause the issue here?
