### ISSUE TITLE
Add more default user interaction

### ISSUE THREAD

**Issue by lancemao** [wbkd/react-flow#3225]
### Please describe the feature that you want to propose

As a UE & Blender developer, I wish ReactFlow can add the following features:
1. To remove a connection (an edge) simply hold ALT and click the output handle
2. To change connection simply hold CTR and drag the output handle, then release to the target. If no target, delete the connection
3. support for CTR+Z and CTR+Y

and for selection and moving, I highly recommend to use Left Mouse Drag to select nodes and use Right Mouse Drag to pan the panel. When you have a large number of nodes, selection becomes a headache

Very good framework, I love it

**Comment by hayleigh-dot-dev** [comment]
Hey there! Great to hear you love the framework 💕 We try and strike a balance between providing common QOL features and leaving the library open for customisation. It might not be the answer you want to hear but it's actually pretty simple to implement some of these behaviours yourself instead of relying on us to add it!

## Remove edges on alt+click

You can hook up a function to `onEdgeClick` in combination with some state to track if alt is being pressed.

```jsx
import { useCallback } from 'react'
import ReactFlow, { useNodesState, useEdgesState, useKeyPress } from 'reactflow'

export default function() {
  const [nodes, setNodes, onNodesChange] = useNodesState(...)
  const [edges, setEdges, onEdgesChange] = useEdgesState(...)
  const altPressed = useKeyPress('Alt')
  const onEdgeClick = useCallback((_, { id }) => {
    if (altPressed) {
      setEdges(edges => edges.filter(edge => edge.id !== id))
    }
  }, [setEdges, altPressed])

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onEdgeClick={onEdgeUpdate}
      onConnect={onConnect}
    />
  )
}
```

I quickly added that to the starter template so you can see it in action [here](https://codesandbox.io/s/delete-edge-on-click-jq8mg3).

## Update connection on ctrl+drag

We actually have an example for updatable edges [here](https://reactflow.dev/docs/examples/edges/updatable-edge/). The idea is the same as above, but we'll toggle whether nodes are updatable whenever ctrl is pressed/released.

```jsx
import { useCallback, useEffect } from 'react'
import ReactFlow, { useNodesState, useEdgesState, useKeyPress } from 'reactflow'

export default function() {
  const [nodes, setNodes, onNodesChange] = useNodesState(...)
  const [edges, setEdges, onEdgesChange] = useEdgesState(...)
  const ctrlPressed = useKeyPress(["Control"]);
  const onEdgeUpdate = useCallback((oldEdge, newConnection) => {
    setEdges((edges) => updateEdge(oldEdge, newConnection, edges))
  }, [setEdges])

  useEffect(() => {
    if (ctrlPressed) {
      setEdges(edges => edges.map(edge => ({ ...edge, updatable: "target" })))
    } else {
      setEdges(edges => edges.map(edge => ({ ...edge, updatable: false })))
    }
  }, [setEdges, ctrlPressed]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onEdgeUpdate={onEdgeUpdate}
      onConnect={onConnect}
    />
  )
```

[Here's a sandbox for that too](https://codesandbox.io/s/update-edge-on-ctrl-drag-rnj5hd?file=/src/Flow.js).

## Undo/Redo

This is actually non-trivial to implement and there are a bunch of ways you could approach this. We don't want to force people down a particular path but we do have a [_pro example_](https://reactflow.dev/docs/examples/interaction/undo-and-redo/) demonstrating one way to do this. 

Depending on what you're working on we may be able to give you access to this example for free: take a look at our FAQ at the bottom over here https://pro.reactflow.dev/

**Comment by lancemao** [comment]
Thanks for your quick reply
