### ISSUE TITLE
onPaneScroll not working with panOnScroll

### ISSUE THREAD

**Issue by Basantrajshakti** [wbkd/react-flow#3250]
### Describe the Bug

I want both the features of onPaneScroll and panOnScroll, but the problem is onPaneScroll doesn't work when zoomOnScroll is enabled, and panOnScroll overwrites it. So when i use panOnScroll, it will enable the zoomOnScroll which I don't wanted to do. 
          I just wanted to scroll the pan and also trigger the scroll event so that I will be able to get the positioning things.

If there is any solution please comment here...

### Steps to Reproduce the Bug or Issue

1. If possible, make it to work with zoomOnScroll.
2. If not, create another function that will be triggered each time on scroll or when zoomOnScroll is disabled.

### Expected behavior

onPaneScroll should work when panOnScroll is enabled or else create another function that will work when panOnScroll is enabled.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bcakmakoglu** [comment]
There might be a misunderstand what `onPaneScroll` means - it is *not* a callback that is triggered through pan on scroll, but triggered when the element itself is scrolled.
That's why you see it triggered when `zoomOnScroll` is enabled, because when you reach the *max* or *min* zoom, you will start *scrolling* the actual pane and not the viewport (which would cause a zoom/pan, depending on the prop you used, i.e. `panOnScroll` or `zoomOnScroll`).

This might be confusing but the actual callback you are (probably) looking for is `onMove`.
This callback is triggered whenever the viewport is "moving" (which includes *zooming* and *panning*).

[Here's an example.](https://codesandbox.io/s/lucid-shirley-f2g588?file=/src/Flow.tsx:1413-1490)

**Comment by Basantrajshakti** [comment]
Yeah, but the problem is `onMove` only works when we 'drag' the viewport or 'zoom' it, and if try to scroll the viewport, it gives me null in event object. I want something that is triggered when I scroll the viewport.

**Comment by bcakmakoglu** [comment]
The `null` you see is the first of two arguments, the first being `MouseEvent | TouchEvent` which in this case is not given (as no mouse/touch event was used).
The *second* argument will give you the viewport position though (check the console in the code sandbox I linked).

<img width="510" alt="image" src="https://github.com/wbkd/react-flow/assets/78412429/3ddf3de8-c3e5-499b-8be7-38e1aa708607">

**Comment by Basantrajshakti** [comment]
Ya Thanks, it worked.
