### ISSUE TITLE
onSelectionChange: passed data is wrong unless ReactFlow is re-rendered via onNodesChange Callback

### ISSUE THREAD

**Issue by FunkMonkey** [wbkd/react-flow#3260]
### Describe the Bug

The data passed to the `onSelectionChange` callback is wrong (basically one selection change behind) if `onNodesChange` does not somehow trigger a re-render. Most examples in the docs use `useNodesState`, which will lead to a re-render somehow, which may be a reason this bug does not appear often.

### Your Example Website or App

https://codesandbox.io/s/quirky-pare-mg43lk?file=/src/App.js:1001-1014

### Steps to Reproduce the Bug or Issue

1. Open the example codesandbox
2. Click on the nodes
3. Look at the console while clicking to see that it is always one behind (e.g. clicking Node 4 after Node 3 will still print Node 3 to the console)
4. uncomment `setCount` call in the `onNodesChange` function and refresh
5. Click on the nodes and look at the console --> printed data is correct, though the callback seems to be called twice

### Expected behavior

`onSelectionChange` should get the correct data independent of whether `oneNodesChange` is used or some other way a re-rendering is triggered.

### Platform

- OS: Windows
- Browser: Firefox 115.02 / Chrome as well
- Reactflow: 11.7.4

**Comment by FunkMonkey** [comment]
p.s. even with the forced re-render multi-selection on mouse-click does not work properly (though it works when using `useNodesState`)

**Comment by FunkMonkey** [comment]
I think this is kinda related to #2649. Going the fully controlled way works indeed, though it is kinda confusing that having nodes without `selected` property still partially works in a weird and wrong way as described in the initial post above...

**Comment by moklick** [comment]
This is not how it works. You have two options:

1. Controlled flow (you are in charge of managing the nodes and edges state)
2. Uncontrolled flow (React Flow cares about managing the nodes and edges state)

If you want to go with a controlled flow using `nodes` and `edges`, you have to use `onNodesChange` and `onEdgesChange`. Otherwise your nodes and edges won't get updated. If you want to go with an uncontrolled flow, you need to use `defaultNodes` and `defaultEdges` (https://codesandbox.io/s/cool-forest-mn7h6d?file=/src/App.js:1229-1301).  

You can read more about it here https://reactflow.dev/docs/concepts/core-concepts/#controlled-or-uncontrolled

**Comment by FunkMonkey** [comment]
Thanks for the quick reply @moklick! 

I understand this now. What I don't quite understand though is, why - in controlled flow -  nodes visually appear selected when clicking on them, even though they don't have the `selected` property set in `nodes`. Shouldn't the appearance be strictly bound to the data?

Thanks again!

**Comment by green-coder** [comment]
@moklick I am also thinking that there is a problem, that in the controlled flow the nodes are still selected when the user clicks on it.

**Comment by bcakmakoglu** [comment]
^Why *shouldn't* they be selected?
If you're applying the selection changes that are given to you via `onNodesChange` the node(s) will be selected.
If you want to prevent that don't apply the changes you don't wanna see applied.

**Comment by FunkMonkey** [comment]
@bcakmakoglu I think @green-coder refers to what I described [previously](https://github.com/xyflow/xyflow/issues/3260#issuecomment-1652016824): even if you don't apply the changes (e.g. the `selected` property), nodes will appear as if they were selected. It seems react-flow is thus not completely controlled in the controlled flow.

**Comment by green-coder** [comment]
The bug doesn't happen on the package `@xyflow/react` version `12.0.3`:

if I am not calling `applyNodeChanges` in `onNodesChange` callback, then the nodes are not automatically selected with 1 re-render of delay as it was described by @FunkMonkey in this ticket.

**Comment by green-coder** [comment]
I spoke too early, the bug is still there but it is now a bit different:

The nodes will still think that they are selected after the user click on them if we don't call `applyNodeChanges` in `onNodesChange`, as clicking on the same node again won't trigger a selection change event.

It feels like the node is preemptively selected internally.
