### ISSUE TITLE
How to pass data / callbacks to a custom edge?

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#357]
Heya, thanks for the library.

I want to have a more complicated menu appearing, if the the user hovers over a custom edge.

Maybe there is already a good way, how to achieve this. I didn't find one. I have the following ideas how it could look like:

### Idea 1

For nodes there is a generic `data` attribute to pass information. It's used for a callback in an example. For edges there is no such attribute. So one could add `data` to the [edge options](https://github.com/wbkd/react-flow#options-1)

### Idea 2

`label` of an edge is defined as string. If it could be any react component, that could also be a solution.

![image](https://user-images.githubusercontent.com/13085980/88272296-c5196700-ccd8-11ea-9a61-1a5472a19c4c.png)

**Comment by moklick** [comment]
Hey @andys8 

thanks for your ideas.

Idea 1:
Could you implement a custom edge and then look up the data with the help of the edge id?

Idea2: 
Right now the EdgeText is rendered as a SVG text and rect element. Maybe it would be better/ more flexible/ easier to implement to if we would implement this as a div overlay. But then we would need a wrapper so that one bring a custom label component and receive the necessary information.. I think if you want to display a special custom label it's better to go with a custom edge.

**Comment by andys8** [comment]
Regarding idea 1: What do you have in mind? If you have the edge id upfront and lookup the data (or create a callback), how would you then pass it and display it in the custom edge? Do you have an example?

**Comment by moklick** [comment]
Could you wrap your flow with a context provider and then receive the data inside your custom edge with the help of a context consumer? But anyway I think you are right and it would be good to add a generic `data` option for edges too. This would make it easier to implement custom edges with a more complex behaviour.

**Comment by andys8** [comment]
Nice! Thank you, @moklick

**Comment by moklick** [comment]
@andys8 it's released in 4.7.0. Let me know if it works for you!

**Comment by andys8** [comment]
Working nicely
