### ISSUE TITLE
Additional behaviour for scrolling

### ISSUE THREAD

**Issue by aludewig** [wbkd/react-flow#359]
Hey, I have some ideas for possible add-ons, that would help to customize the graph:

- option to move the graph when scrolling on the mouse (instead of zooming) -> maybe that you can choose if you either want to move, zoom or do nothing when scrolling
- possibility to disable a certain direction for moving, e.g. that you only allow to move the graph vertically
- when mouse scrolling triggers to move the graph, you could add the option to zoom on scroll+keypress

**Comment by ThomasVlaar** [comment]
![Screenshot 2020-09-01 at 12 13 03](https://user-images.githubusercontent.com/56717030/91837428-84ecc300-ec4c-11ea-8862-c12a50a71388.png)

Hi There! We would love to see a scrollable canvas with the mouse! We are currently building a flow builder, and when it's becoming bigger and bigger our users expect to use the scroll to move the canvas. Are there any plans to work on this feature?

**Comment by pranithasri** [comment]
Hi  @ThomasVlaar  , Did you use ReactFlow for this.If so,Is it possible  handles and draw edges?.please let me know.Iam curious about that.

**Comment by moklick** [comment]
We added a `onPaneScroll` handler. This could help you to implement a custom scroll logic.

**Comment by amcdnl** [comment]
@moklick - Any tips on best way to implement this?

**Comment by roywillemse** [comment]
@moklick Hey, I'm a colleague of Emiel and Thomas.  First of all thanks for the work you're doing with Reactflow, we really like the package :).

There is one thing we are struggling with, we tried implementing the `onPanelScroll` to fix scrolling in the canvas but this didn't give us the result we are looking for.

[screenrecordings of the scrolling implementations](https://imgur.com/a/ZWiVD6d)

**Option 1: Scrolling using the onPaneScroll function**
In the first screen recording you can see that the entire page is being scrolled because the browser can't know that this is a spot that can be scrolled. This is a bit of an exaggeration, we can of course speed up the scroll speed but this will always be an issue with this approach I think.

Another issue we encountered with this option is that scrolling with a mouse wheel needs a much higher speed to scroll effectively trough the canvas as oppose to a trackpad. We couldn't find a happy medium for both mouse and touchpad scrolling.

**Option 2: Scrolling using native scrollbars**
We tried to add native scrollbars to check if this would be a viable option and to see what works and what doesn't. 
To test this we added the following to the `ReactFlow` component:
`style={{ maxHeight: '100%', overflow: 'scroll' }}`

I think we do prefer option 2 to use native scroll behaviour but there are things that will break with this implementation as you can see in the second screencast.

What do you think? and what are your plans to create scroll functionality in ReactFlow if there are any? Perhaps this is something we could wait for?

**Comment by chrtze** [comment]
We have not yet started working on this but it is definitely something we want to have in the library. I think both of your versions look quite good already. Can you explain what is not working in option 2 exactly? Did you try fixing the behaviour in option 1 with CSS (something like `position: fixed` for the root element)?

Anyway, is there any way you can reproduce both examples in a codesandbox or so? That may be very helpful for us to implement the scrolling feature into the library.

Thanks!

**Comment by roywillemse** [comment]
@chrtze Hey Christopher, thanks for the quick response. If it is possible to fix option 2 easily, we're very interested.

I created a codesandbox with the two options, hope this helps to explain: https://codesandbox.io/s/reactflow-scrolling-implementation-2kuro?file=/src/App.js

Thanks for your efforts, we appreciate it very much!

**Comment by chrtze** [comment]
We have implemented a first version of the scroll to pan feature. You can try it out by installing the pre-release: `npm install react-flow-renderer@next`. The feature is enabled like this: `<ReactFlow elements={elements} panOnScroll />`.

Feedback is very appreciated :)

**Comment by ReachTheWeb** [comment]
@chrtze Hey Christopher, wow very nice 👍  

I tried this in the codesandbox as well and it works great: https://codesandbox.io/s/reactflow-scrolling-implementation-using-next-xhgq6?file=/src/App.js

Couple of questions:

1. As you can see in the codesandbox the rest of the page is still scrolling when you scroll a lot, do you know a solution for this? Maby we could fix this with CSS like you suggested before? I tried a couple of things but I couldn' t get this to work.

2. Would it be possible to change the speed of the scrolling?
If this isn't easy to implement I think it's fine as it is now.


Great that you implemented this so quickly, we're very happy and impressed :)

**Comment by roywillemse** [comment]
@chrtze Hey Christopher, wow very nice 👍  

I tried this in the codesandbox as well and it works great: https://codesandbox.io/s/reactflow-scrolling-implementation-using-next-xhgq6?file=/src/App.js

Couple of questions:

1. As you can see in the codesandbox the rest of the page is still scrolling when you scroll a lot, do you know a solution for this? Maby we could fix this with CSS like you suggested before? I tried a couple of things but I couldn' t get this to work.

2. Would it be possible to change the speed of the scrolling?
If this isn't easy to implement I think it's fine as it is now.


Great that you implemented this so quickly, we're very happy and impressed :)

**Comment by chrtze** [comment]
@roywillemse 1: I can reproduce that the page is "bouncing" when I use the trackpad to scroll the graph. with a regular mousewheel, it works fine. I fixed this in our examples by using `body { overflow: hidden }`. but not so sure if this is a good approach in your case. https://stackoverflow.com/questions/28103125/disable-inertia-scroll-for-single-page-webapp

2: That's a good idea. I think it would not be too complicated to implement it, we would need some parameter like `scrollSpeed={1.5}`. Maybe d3-zoom has something built in, I will check that.

**Comment by roywillemse** [comment]
@chrtze 1: Thanks for the link, I tested this and we can add: `overscroll-behavior-y: none; on the body to fix this. Very nice.

2: If that would be possible and easy to implement that would be awesome, a scollSpeed parameter would be perfect.

Thanks!

**Comment by chrtze** [comment]
There is a possibility in d3-zoom to change the wheelDelta: https://github.com/d3/d3-zoom#zoom_wheelDelta
I only need to figure out how a property for this could look like in react-flow.

**Comment by chrtze** [comment]
released in [7.0.0](https://github.com/wbkd/react-flow/releases/tag/7.0.0). we also introduced a new property `panOnScrollSpeed` to control the speed of the movement. The page bounce when using the trackpad has also been fixed in this version by using `event.preventDefault` and `event.stopPropagation`, same as in d3-zoom.

**Comment by emielwit** [comment]
Awesome job, this solution perfectly fits our needs. Really appreciate the effort 🚀.

**Comment by ThomasVlaar** [comment]
Thank you very much @chrtze ! We're very happy with the end result. Keep up the good work!
