### ISSUE TITLE
Node position not matching the nodes list and rendered node

### ISSUE THREAD

**Issue by StellarLogic** [wbkd/react-flow#4298]
### Describe the Bug

I am generating dynamic node position using sub layout but generate position and rendered ui node position is not same 

https://codesandbox.io/p/sandbox/react-flow-6rlsqq?file=%2Fsrc%2Findex.js

![image](https://github.com/xyflow/xyflow/assets/66798245/d0648702-bc33-435f-8254-2764429ab44f)

### Steps to Reproduce the Bug or Issue

shared code sandbox for code 

### Expected behavior

UI node position should match the provided node object position

### Platform

- OS: windows 11
- Browser: edge
- Version: 125.0.2535.51

**Comment by bcakmakoglu** [comment]
You didn't describe *what the expected position is supposed to be*.
The screenshot doesn't explain what you expected to happen.

Maybe there's a misunderstanding how `position` works for subflows/nested nodes.
A node that has **no `parentId`** set will be positioned *relative* to the viewport, meaning, if the viewport wasn't moved, a position of `x: 0, y: 0` would be the top-left corner of the viewport.
A node that has a `parentId` set will be postioned *relative to it's parent-node*, meaning a position of `x: 0, y: 0` would be the top-left corner of *the parent node* and not the viewport.

**Comment by bcakmakoglu** [comment]
As I previously stated, since you are using `parentId` you are changing the relation of `position` from viewport to parent-node.

> Maybe there's a misunderstanding how position works for subflows/nested nodes.
A node that has no parentId set will be positioned relative to the viewport, meaning, if the viewport wasn't moved, a position of x: 0, y: 0 would be the top-left corner of the viewport.
A node that has a parentId set will be postioned relative to it's parent-node, meaning a position of x: 0, y: 0 would be the top-left corner of the parent node and not the viewport.

<img width="448" alt="image" src="https://github.com/xyflow/xyflow/assets/78412429/53e17a55-ba3c-44b9-90e3-8614ffba9065">

You will have to consider the parent position in your calculations otherwise the position you expect is never going to match the position you get - that is simply how subflows work and this is *not a bug*.

[Here's a sandbox](https://codesandbox.io/p/sandbox/react-flow-forked-v4dxkv?file=%2Fsrc%2Fcomponents%2Futils.js%3A82%2C31) where I (naively) just subtract the parent positions, maybe that looks a little closer to what you wanted to see.
