### ISSUE TITLE
Percent Zoom in Controls

### ISSUE THREAD

**Issue by wdfinch** [wbkd/react-flow#433]
A helpful tool in controls would be zoom to percent. This would be a text input that would serve two purposes: 

1. Show the current zoom level (between 0 and 100%)
2. Easily move to a percent (so the user doesn't need to click the zoom in/zoom out button many times)

Would be great if something like this could be added.

**Comment by moklick** [comment]
It's a good idea but we will not implement this feature because we want to keep the core features as small as possible.  It should be relatively easy to implement a feature like this and you could publish it so that other people could use it too. Check out the controls component to get an idea how you could build your custom zoom control.

**Comment by wdfinch** [comment]
Sounds good. I noticed there are zoom in and zoom out helper methods. Would be possible to add a zoom to helper method that takes a number between zoom min and zoom max?

**Comment by moklick** [comment]
The `reactflowInstance` now also has a `zoomTo` function where you can pass a zoomLevel between min and max zoom. It's released in v5.4.0

**Comment by moklick** [comment]
With v9.4.0 you can easily extend the controls: https://reactflow.dev/docs/api/components/controls/#extended-controls
