### ISSUE TITLE
fitView() on onLoad doesn't seem to act, but works with Control Panel

### ISSUE THREAD

**Issue by YoannBuzenet** [wbkd/react-flow#533]
Hello there,

I am currently working on the fitView() method on my diagram, but I see that it doesn't seem to fit on onLoad().

I am doing this, following the doc :
```
const onLoad = (reactFlowInstance) => {
    reactFlowInstance.fitView();
}
```

But it doesn't happen. But when I click on the fitView button on the control, it does work !

Here is how I use the props in the component : 
```
<ReactFlow
        elements={elements}
        elementsSelectable={diagramMode !== "View"}
        onLoad={onLoad}
        nodesDraggable={nodesDraggableState}
        paneMoveable
        zoomOnScroll
        arrowHeadColor="#206584"
        nodesConnectable={nodesConnectableState}
        defaultPosition={[0, 0]}
        defaultZoom={1}
        onNodeDragStop={onNodeDragStop}
        onConnect={onConnect}
        onElementClick={openForm}
        onElementsRemove={onElementsRemove}
        deleteKeyCode={46}
      >
        <MiniMap
          nodeColor={(node) => {
            switch (node.type) {
              case "input":
                return "red";
              case "default":
                return "#00ff00";
              case "output":
                return "rgb(0,0,255)";
              default:
                return "#eee";
            }
          }}
        />
        <Controls />
      </ReactFlow>
```

I tried adding padding as a parameter, to do as the Control Panel . Here is the code of the control panel  I found in the sources : 

```
{showFitView && (
        <div
          className="react-flow__controls-button react-flow__controls-fitview"
          onClick={() => fitView({ padding: 0.1 })}
        >
          <FitviewIcon />
        </div>
      )}
```
But even when adding padding like this, it does not change the behaviour.
I tried to look at the older issues but couln't find something related.

Would you have any idea about the source of this ?

Thank you,
Yoann

**Comment by moklick** [comment]
This is strange. Everything looks good and we are using the fitView function in our examples inside the onLoad handler too. Can you create a codesandbox so that we can check the code?

**Comment by KutnerUri** [comment]
happening to me too. Fixed it by adding setTimeout, i.e.
```tsx
onLoad={(instance) => setTimeout(() => instance.fitView(), 0)}
```

**Comment by moklick** [comment]
Thanks for the hint regarding the `defaultPosition` prop. Could you check v6.0.0 ?

**Comment by odus-ex** [comment]
I tried it out, fix not working for me in v6.0.0

**Comment by KutnerUri** [comment]
same for me

**Comment by nileshlande12** [comment]
Same issue started facing after updating it to 6.1.1, 
for me control panel is also not working, it actually taking maxZoom which I'm passing as 3,
if I remove maxZoom props it worked.
I also see such issue in example /custom-node when doing reactFlowInstance.fitView();
Note: I'm rendering graph vertically.

**Comment by YoannBuzenet** [comment]
Hello,

I think it was my fault, I was displaying the ReactFlow component before having the array of data ready. I'm getting the data from API and treating it before setting it in the array of ReactFlow.

I think it did trigger onLoad before it had the right data to fit on. I added a flag to make it display after data was treated + added a setTimeout to be sure, and now it works most of the time.

**Comment by Jc2k** [comment]
I hit this something like this too with the custom node example. In that case it was because of the useEffect() - i guess when onLoad was called the useEffect hadn't run and called setElements yet. Now i just need to figure out how to call fitView when setElements is called! Maybe a useEffect that depends on the value of elements? But how would i get the instance in that case...?

**Comment by tafelito** [comment]
just wanted to add that this happens to me too in version `6.2.2` and in order to fix it I use `requestAnimationFrame` instead of `setTimeout` but i has the same effect. In my case I'm not changing the defaultPosition. And even if I do set a defaultPosition, it doesn't do anything when using it with `fitView`

**Comment by Jc2k** [comment]
As my case was caused by `elements` being ready when the component was first rendered I worked around it in the end by just not trying to render the ReactFlow component until i had some elements to draw and then it worked fine. E.g. adapting the example from above, i just:

```
{elements && <ReactFlow
        elements={elements}
        elementsSelectable={diagramMode !== "View"}
        onLoad={onLoad}
        nodesDraggable={nodesDraggableState}
        paneMoveable
        zoomOnScroll
        arrowHeadColor="#206584"
        nodesConnectable={nodesConnectableState}
        defaultPosition={[0, 0]}
        defaultZoom={1}
        onNodeDragStop={onNodeDragStop}
        onConnect={onConnect}
        onElementClick={openForm}
        onElementsRemove={onElementsRemove}
        deleteKeyCode={46}
      >
        <MiniMap
          nodeColor={(node) => {
            switch (node.type) {
              case "input":
                return "red";
              case "default":
                return "#00ff00";
              case "output":
                return "rgb(0,0,255)";
              default:
                return "#eee";
            }
          }}
        />
        <Controls />
      </ReactFlow>}
```

**Comment by chrtze** [comment]
This seems to happen when the elements are changed after ReactFlow gets mounted (e.g. with `useEffect` like in the custom node example). That is because the onLoad handler gets called before the new elements are passed to the component. You can workaround this by waiting for the elements to change in an extra `useEffect` hook. Minimal example: https://codesandbox.io/s/unruffled-ishizaka-fhljt?file=/src/App.js

**Comment by ahgittin** [comment]
For anyone stumbling across this because `fitView` doesn't seem to be working, the answer in my case was to wait for `useNodesInitialized` [1] to return `true` after changing the nodes.

Simply calling `setNodes(...)` then `reactFlowInstance.fitView()` doesn't act on the nodes you just set.  It can be a few react update cycles before the nodes you set are fully settled inside RF, so waiting on one `useEffect` isn't good enough.  Even `setTimeout` didn't work unless the timeout was at least about 100ms for me.  But a `useEffect(()=>{ ... fitView ... }, nodesInitialized)`  worked a charm.

(Also for anyone wondering about `onLoad` in OP -- it's now called `onInit`.)

[1] https://reactflow.dev/docs/api/hooks/use-nodes-initialized/

**Comment by stallboy** [comment]
> For anyone stumbling across this because `fitView` doesn't seem to be working, the answer in my case was to wait for `useNodesInitialized` [1] to return `true` after changing the nodes.
> 
> Simply calling `setNodes(...)` then `reactFlowInstance.fitView()` doesn't act on the nodes you just set. It can be a few react update cycles before the nodes you set are fully settled inside RF, so waiting on one `useEffect` isn't good enough. Even `setTimeout` didn't work unless the timeout was at least about 100ms for me. But a `useEffect(()=>{ ... fitView ... }, nodesInitialized)` worked a charm.
> 
> (Also for anyone wondering about `onLoad` in OP -- it's now called `onInit`.)
> 
> [1] https://reactflow.dev/docs/api/hooks/use-nodes-initialized/

yes , after layout then `setNodes` then call  `reactFlowInstance.fitView()` does not work. setTimeout work for me. but that's not a good solution. it introduce fickers since the view change suddenly in one frame.  
@moklick can you give a fitView utility funtion that accept newNodes as parameter (not nodes snapshot) , let us do the layout and fit view in one render and avoid the flickers.

**Comment by Iaotle** [comment]
I'm also experiencing this issue, `fitView` fits to where the nodes used to be before layouting. using `useEffect` as described above doesn't work for me, only `setTimeout` does.

**Comment by abdullahalnomandev** [comment]
Fixed it by adding `onInit` and  `useEffect`. Those steps are:


```
  const [reactFlowInstance, setReactFlowInstance] = useState(null);

  const onInit = (rf) => {
    setReactFlowInstance(rf);
  };

  useEffect(() => {
    if (reactFlowInstance && nodes?.length) {
      reactFlowInstance.fitView();
    }
  }, [reactFlowInstance, nodes?.length]);
```

      <ReactFlow
        ... 
        onInit={onInit}
      >

**Comment by atumas-bananamilk** [comment]
This works perfectly for me:

```
const [initialLoading, setInitialLoading] = useState<boolean>(true)

useEffect(() => {
  setInitialLoading(false)
}, [])

return (
  <>
    {! initialLoading && (
      <ReactFlow />
     )}
  </>
)
```

**Comment by aes421** [comment]
> As my case was caused by `elements` being ready when the component was first rendered I worked around it in the end by just not trying to render the ReactFlow component until i had some elements to draw and then it worked fine. E.g. adapting the example from above, i just:
> 
> ```
> {elements && <ReactFlow
>         elements={elements}
>         elementsSelectable={diagramMode !== "View"}
>         onLoad={onLoad}
>         nodesDraggable={nodesDraggableState}
>         paneMoveable
>         zoomOnScroll
>         arrowHeadColor="#206584"
>         nodesConnectable={nodesConnectableState}
>         defaultPosition={[0, 0]}
>         defaultZoom={1}
>         onNodeDragStop={onNodeDragStop}
>         onConnect={onConnect}
>         onElementClick={openForm}
>         onElementsRemove={onElementsRemove}
>         deleteKeyCode={46}
>       >
>         <MiniMap
>           nodeColor={(node) => {
>             switch (node.type) {
>               case "input":
>                 return "red";
>               case "default":
>                 return "#00ff00";
>               case "output":
>                 return "rgb(0,0,255)";
>               default:
>                 return "#eee";
>             }
>           }}
>         />
>         <Controls />
>       </ReactFlow>}
> ```

@Jc2k I spent so long trying to figure out why fitView wasn't working for me with dagre layout and this solved it!

**Comment by devHamzza** [comment]
```
<ReactFlow
onInit={(instance) => {
            setTimeout(() => {
              instance.fitView({
                maxZoom: 1,
              });
            }, 0);
}}
>
...
</ReactFlow>
```

This resolved the issue for me.
