### ISSUE TITLE
[FEATURE] Improve Hit Detection

### ISSUE THREAD

**Issue by amcdnl** [wbkd/react-flow#615]
## Request
It would be nice if as you were dragging a link to a node, if it got close to one it would highlight the closest node.

**Comment by amcdnl** [comment]
Checkout how this example works - https://github.com/alyssaxuu/flowy

**Comment by moklick** [comment]
I really like this behaviour but we will not integrate it to the core. I think it's mostly interesting for drag and drop applications where you drag a node above another one and create a node with a connection afterwards. Since you would need to implement all this stuff by yourself you could also find out if there is an intersection with a node below the dragged one.
