### ISSUE TITLE
Can a custom edge include more complex UI elements other than text?

### ISSUE THREAD

**Issue by TheOnlyArtz** [wbkd/react-flow#722]
Hello, we're looking to implement a specific design 
![image](https://user-images.githubusercontent.com/30025874/100233998-22495180-2f33-11eb-9e87-f7f9781920b0.png)

Is it possible to implement it on the current versions of react-flow? The closest thing we've seen is to use the label property in the Edge component, but it only accepts a text component and we would like to use a more extensive component.

**Comment by chrtze** [comment]
hi @TheOnlyArtz, unfortunately this is not possible at the moment, as only strings are supported for this property. we are planning to change the rendering of the edge labels to allow svg elements to be rendered as label (#425). when that is implemented, you could use `foreignObject` to add more complex ui elements.

**Comment by moklick** [comment]
It is possible when you implement a custom edge type. We export [several edge utils](https://reactflow.dev/docs/api/edge-utils/) so that you don't need to start from scratch. You can find an implementation of a custom edge [here](https://reactflow.dev/examples/edges/). As @chrtze pointed out you would need to use `foreignObject` inside your custom edge.
