### ISSUE TITLE
[Proposal]: Need support to accept JSON object instead Array for elements

### ISSUE THREAD

**Issue by pradeepravi-cse** [wbkd/react-flow#743]
Currently we are using array of elements as input to the react-flow-render. Its very difficult to update one element properties

e.g

I want to update one node object based on the click or whatever.

1. Curretly i need to get the index of the clicked node first
2. Clone the entire elements and update the node based on the index we got from the first point
3. update the entire elements

### Proposal: 
If we change the elements to Object. like the below. it will be easy to update the tree

```
{
  "etQRriCEb44snkFQIQ6_r": {
    "id": "etQRriCEb44snkFQIQ6_r",
    "type": "customNode",
    "data": {
      "label": "custom Node",
      "color": "#800080"
    },
    "position": {
      "x": 597,
      "y": 162
    }
  }
}
```

**Comment by moklick** [comment]
Hey @pradeepravi-cse 

It's a good point. We are thinking about using a Map as the new data structure for nodes #681.

**Comment by jwang0306** [comment]
I would like to see it in Object because of the spreading and restructuring syntax.

**Comment by MonliH** [comment]
I also would like to see an object here, as it seems to make more sense. I think this would improve performance a lot, especially when there are very many nodes: looking for an element with a given id on an array is `O(n)` (the more nodes, the slower it gets), while on an object it's `O(1)` (constant time).

**Comment by taranek** [comment]
@moklick  - can you tell us something more about this proposal status? I do realise it'd be time consuming, but it'd be nice to have an update, so that I can decide whether I'd have to do my own implementation to patch this.

**Comment by xixixao** [comment]
Imho nothing is preventing you from using an Object / Map as your data storage, but you need to map from it to the data that React Flow supports (and map into it in callbacks).

Immer can also be used to simplify mutations (having elements split between nodes and edges will help).

**Comment by cliffordfajardo** [comment]
I like the map data structure idea.  If you need it to be an array, its quite easy to convert to an object as well:

```ts
const someMap = new Map()
const nodes= Array.from(someMap.values())
```

With regard to what @pradeepravi-cse said:

> I want to update one node object based on the click or whatever.
> Currently i need to get the index of the clicked node first
- It seems like in v10, nodes and edges will be split out into two separate sources so traversing the list of items will be a lot less (_so faster performance since less iteration *potentially_ 🎉 )

  ```ts
   const nodes = [ {  id: "1",  data: {  label: "Node1"  }  },];
   const edges = [{ id: "EDGE_ID_1", source: "some_id", target: "some_id" }, ...];
   <ReactFlow nodes={nodes} edges={edges} />
   ```
- I would venture to say that most `react-flow` graphs will have less than 500 elements showing on the graph (_usually after 50 items graphs like these can messy so people only display a small of data at a time in practice_). Even for 500-1000 nodes, iterating over the array to find the index should be very quick:

```ts
const nodes = Array(1001).fill(1).map((value, index) =>  { id: index })
const startTime = performance.now()
  nodes.find(node => node.id === 1000)
const endTime = performance.now()

console.log(`Call to doSomething took ${endTime - startTime} milliseconds`) 
// less than 1 millisecond for 1000 items
```

But as mentioned in v10 since nodes will be a Map  we don't need to worry about iterating a whole list

<br />

> Clone the entire elements and update the node based on the index we got from the first point
 - when you say `clone` are you referring to this type of behavior?

```
const nodeToUpdate = elements.find(node => node.id === someID);
nodeToUpdate.x = 100;

let updatedElemebts = [...elements] // re-assign before passing back to `<ReactFlow>` so react knows the nodes array object changed.
// ^ this operation doesn't clone or re-recreate items internally , it re-assigns array pointer in memory pointing to the new array

```

If that's not what you mean forgive me for misunderstanding 😅 



With regard to the mention of using an Object instead of a Map since it provides the added benefit of destructuring

```ts
const chart = {
  // other properties 
  nodes: {
    node1: {
      id: 'node1',
      position: { x: 300, y: 100,},
    },
    node2: {
      id: 'node2',
      position: { x: 300, y: 300,},
    },
  },
}
```

I like the idea of being able to spread, but I'm missing how it makes it easier to update the nodes list by making use of the spread operator:


```ts
const chart = {
  // other properties 
  nodes: {
    node1: {
      id: 'node1',
      position: { x: 300, y: 100,},
    },
    node2: {
      id: 'node2',
      position: { x: 300, y: 300,},
    },
  },
}

const nodes = chart.nodes;
const newNode3 =  { id: 'node3',  position: { x: 300, y: 300,} },

chart.nodes.node3 = newNode3 // update

const newNodes = { ...nodes}
chart = {...newNodes}
```


but it seems like you likely won't ever be

**Comment by chrtze** [comment]
We have reworked the data structure for the elements in v10 and split it into `nodes` and `edges`. This should give you more flexibility. We decided against changing it into a map or object. You can read more about the decision process here: https://github.com/wbkd/react-flow/discussions/960
