### ISSUE TITLE
Nodes renaming 

### ISSUE THREAD

**Issue by MuhammadAichee** [wbkd/react-flow#758]
How can I rename my existing node ?

**Comment by moklick** [comment]
Hi @MuhammadAichee, 

there is no built-in node renaming feature. You would need to build a UI and updates your elements (like in this example https://reactflow.dev/examples/custom-node/).   

We don’t have the resources to answer all questions regarding the usage of the library or special features build on top of react-flow. Please post your questions at stackoverflow with the tag `react-flow`, so that we can focus on bugs and feature requests in the github issues.

**Comment by moklick** [comment]
I added an example of how to [update node attributes](https://reactflow.dev/examples/update-node/) and added a note on the [node options site](http://localhost:8000/docs/api/nodes/).
