### ISSUE TITLE
Chart pane overflow scroll behavior

### ISSUE THREAD

**Issue by Gunner17** [wbkd/react-flow#797]
Is it possible to add overflow scrolling behavior in the flow chart pane? 
Sometimes we may have to restrict the Pane size (height and width), but the chart may exceed the width and height of the pane. I would like the user to scroll and see any node elements that have overflown the chart pane. Can we achieve something like that through CSS (**without using pane zoom or pane move features**)? Illustration below.

<img width="482" alt="Screen Shot 2020-12-22 at 6 35 49 PM" src="https://user-images.githubusercontent.com/11354728/102953419-1b582500-4486-11eb-8afe-e1bdc54aa401.png">

**Comment by moklick** [comment]
When `zoomOnScroll ` and `panOnScroll` is false you could handle this by dynamically changing the height of the pane depending on the bounds of the nodes I guess.. but it's relatively complex. When a node moves out of the canvas in the upper area you would also need to change the height but you would then need to update the scroll position of the parent in order to be able to scroll up to see the node.. Maybe you can can find a better solution than a scrolling container for your problem here.

**Comment by Gunner17** [comment]
Thanks for the suggestions 👍. 
I may try one of these approaches: 
[ solution 1] As you stated, dynamically changing the height of the pane depending on the bounds of the nodes. 
[ solution 2] only allow panOnScroll when when a node moves out of the canvas. To be decided based on the bounds of the nodes
