### ISSUE TITLE
NodeType

### ISSUE THREAD

**Issue by rajeshwari-differenz123** [wbkd/react-flow#798]
hi,
Is there any other nodeType except "special" and "SelectorNode".
also how can i manage two NodeType in one <ReactFlow> tag

**Comment by moklick** [comment]
Hi, this is not an issue with react flow. It's documented how you can create custom node types. `special` and `selectorNode` are just example implementations. You can name the custom node types however you want.

We don’t have the resources to answer all questions regarding the usage of the library. Please post your questions at stackoverflow with the tag `react-flow`, so that we can focus on bugs and feature requests in the github issues.

**Comment by rajeshwari-differenz123** [comment]
i don't have 1500 points on stackOverflow to creat new tag react-flow
