### ISSUE TITLE
How to add a "central" Edge label?

### ISSUE THREAD

**Issue by OrhanTozan** [wbkd/react-flow#803]
![image](https://user-images.githubusercontent.com/16029639/103153747-fe2b9b00-4792-11eb-8179-99a93aa78f83.png)

I want to have one single label for all edges, just like the picture. What would be the best way to achieve this?

**Comment by RickeyWard** [comment]
Is your issue a) getting just 1 label, b) the position of the label, or c) trying to have this automatically handled by the rendering?

a) Without making a custom edge you can specify a label only on one of the edge elements. +c) Creating a custom edge, you can loop through the all edges and determine if they have the same source handle, sort them and hide the label on all but the first. this could a performance impact, some optimization/memoization may be needed.

b) Without making a custom edge you can specify a `labelStyle` on the edge and move its position, be default it's in the "center' between the source and target, using transform you can adjust it's position. +c) using a custom edge you can modify where the EdgeText component is centered by using any way you choose to calculate the centerx and centery.

c) copy wbkd\react-flow\src\components\Edges\SmoothStepEdge.tsx into your project (remove the typescript bindings if needed), Swap `getCenter` for `getEdgeCenter` (the exported version instead of the internal version) and then implement the +C  suggestions from a) and b)

**Comment by moklick** [comment]
Thanks for your help @RickeyWard

**Comment by tonyabracadabra** [comment]
Hi @moklick Did you got a way to implement it? I tried )c in what @RickeyWard was suggesting but the label is still not centered
