### ISSUE TITLE
onNodeDragStart method is executed on Node Click

### ISSUE THREAD

**Issue by agarwal00s** [wbkd/react-flow#804]
onNodeDragStart method gets executed with onElementClick as well. not able to distinguish between node drag start and node click

**Comment by moklick** [comment]
We already thought about this and we didn't find a good solution. In the moment when you click on a node we don't know if you will start to drag it or not. When you just drag a node we don't fire the `onClick` event because we know that you just dragged the node. You could try to set a timeout on drag start and cancel it with the click handler. 

I will close this issue because the behavior is intended.
