### ISSUE TITLE
Question: Highlight / style connection target on hover

### ISSUE THREAD

**Issue by Pitchlab** [wbkd/react-flow#889]
Hello,

I have been looking at the source but I can't figure out how to do this.

I have nodes that can only accept specific nodes to be connected to them. This I made work. But I would like to warn the user when they try to connect a node to an 'illegal' target, while they are dragging the connector line over it, showing an icon or styling the target connection point. For this, I would need some event that fires while the user is still dragging but is over a target point. Does that exist? And if not, can it be added or does that require editing the source? 

Kind regards

**Comment by moklick** [comment]
Hey @Pitchlab 

you can use the `isValidConnection` prop of the [Handle component](https://reactflow.dev/docs/api/handle/). We have an example here: https://reactflow.dev/examples/validation/. Is this what you are looking for?

**Comment by Pitchlab** [comment]
Ah thanks! That makes sense. Cheers

**Comment by clarkmcc** [comment]
Sorry to dig up an old issue, but I'm trying to do something similar but can't seem to find a built-in way to do this. I'd like to highlight only the handles that are available for connection. The problem is that `isValidConnection` seems to run on only when the edge is held over top of the handle. I'd like to highlight the available handles across my flow when I even start to pick up an edge. Any ideas?
