### ISSUE TITLE
Toggling two output handles will not update the edges

### ISSUE THREAD

**Issue by andys8** [wbkd/react-flow#916]
A custom node with multiple outputs is used. Two of these outputs handles are toggled. This means the same ids are used, but switched. The node itself will re-render and the output labels are updated. The output ids are switched correctly in the DOM.

## Issue

The edges are should be switched. They aren't.

## Debugging

* They are actually re-rendered but in the old position (verified this by rendering in random color).
* Saving the state to a database and refreshing the website, will render the graph with switched edges correctly.
* Also rendering 0 outputs, then delay, and then render the switched outputs will lead to correctly rendered edges.

## Minimal Example

Sadly I'm not able to provide code from a private repository and also I didn't manage to reproduce the same setup with a minimal example.

## Related issues and documentation

I noticed there are similar issues (https://github.com/wbkd/react-flow/issues/805, https://github.com/wbkd/react-flow/issues/693) and there are docs regarding updating [nodes](https://reactflow.dev/examples/update-node/) and [edges](https://reactflow.dev/examples/updatable-edge/). The project I'm working on is written in PureScript and not using Hooks for state management. This means it's not straight forward to translate the suggested examples to a solution in PS. Creating new objects could for example result in the same objects being reused if implementation is clever (not sure).

## Help

Under the current assumptions I'd guess there is some internal caching happening for edges. Especially edges between handle id A and handle id B don't seem to be re-rendered even the handle id A is now at a different position than before.

I'd be grateful for information regarding the following questions:

* Can you confirm memoization could lead to this issue?
* Where in the code is this specific memoization happening?
* Which parameters need to be changed to trigger rendering these edges being rendered correctly?
* Would it make sense to compare more than the current properties to verify an edge didn't change?

**Comment by ankur-zymr** [comment]
@andys8 I am facing the same issue, have you got the solution for this?

**Comment by andys8** [comment]
I don't have a solution, but the workaround is to do this:

> Also rendering 0 outputs, then delay, and then render the switched outputs will lead to correctly rendered edges.

This way it will flicker, but will be shown correct afterwards.

Since you encounter the same problem, would it be possible to link to the code or add an example to reproduce it?

**Comment by wladimiiir** [comment]
I am experiencing similar problem - nodes are updated correctly, but edges connected to the new Handles are incorrectly placed. Currently I am using different `key` property of `ReactFlow` after elements are updated as a workaround.

**Comment by andys8** [comment]
I can hopefully give it a try soon and provide feedback :)

I've 2 questions:

## 1. Example

There is an example called `UseUpdateNodeInternals`: https://github.com/wbkd/react-flow/blob/main/example/src/UseUpdateNodeInternals/index.tsx

If I click around it looks like the second button is changing nothing. How to test it? What should happen?


https://user-images.githubusercontent.com/13085980/109546042-f6a5ac80-7ac9-11eb-9fe8-437b488dc4a6.mp4

## 2. Implementation

And the implementation of `useUpdateNodeInternals` looks like a way to work around some memoization happening in this case. Could you share some technical details, what the difficulties are in this case? And how the workaound can be used: Does there need to be time between rendering the nodes wrongly and triggering the resizing?

```js
function useUpdateNodeInternals(): UpdateNodeInternals {
  const updateNodeDimensions = useStoreActions((actions) => actions.updateNodeDimensions);

  return useCallback<UpdateNodeInternals>((id: ElementId) => {
    const nodeElement = document.querySelector(`.react-flow__node[data-id="${id}"]`);

    if (nodeElement) {
      updateNodeDimensions([{ id, nodeElement, forceUpdate: true }]);
    }
  }, []);
}
```

**Comment by wladimiiir** [comment]
> In v9.1.0 we added a `useUpdateNodeInternals` hook that can be used to update the node internals programatically.
> 
> Usage:
> 
> ```js
> import { useUpdateNodeInternals } from 'react-flow-renderer';
> 
> // ....
> 
> const updateNodeInternals = useUpdateNodeInternals();
> 
> // somewhere in your app
> updateNodeInternals('node-id');
> ```
> 
> Does this solve your issue?

Yes, that solves my issue. Thank you for quick response.

**Comment by moklick** [comment]
Hey @andys8 

1. When you toggle the second handle and try to connect it with another node (you can create a new node by clicking on the pane), the edge is drawn incorrectly. After you click the `update node internals` button, that calls `updateNodeInternals` for the node that is on the pane from the beginning, the edge is drawn correctly because the handles are recalculated.

2. I am using `useCallback` here to prevent a reinitialization of the returned function on every render. If I would do: 
 
```js 
function useUpdateNodeInternals(): UpdateNodeInternals {
  const updateNodeDimensions = useStoreActions((actions) => actions.updateNodeDimensions);

  return (id: ElementId) => {
    const nodeElement = document.querySelector(`.react-flow__node[data-id="${id}"]`);

    if (nodeElement) {
      updateNodeDimensions([{ id, nodeElement, forceUpdate: true }]);
    }
  };
```

this function would be recreated every time the component that uses this hook would render. We don't need to wait for anything here since it's called programatically. You should call it only when you are sure that your node is updated with the new handle inforamtion.

**Comment by andys8** [comment]
Thanks for the reply. Will give it a shot.

**Comment by darkojelen** [comment]
Based on this conversation and useUpdateNodeInternals example I tried to solve my problem. I need multiple Handle on node, each with only one connection allowed and when last Handle is connected, new is automatically added. Useupdatenodeinternals example was great help. 

![example](https://user-images.githubusercontent.com/28961283/109967412-add03c80-7cf1-11eb-87b8-965bdc8180ae.jpg)

It seems that my solution is working, but I notice few strange behaviour. For 1, 2 or 3 Handles there is no warning. But when node has 4 or more Handles there is a warning, but no visible error on screen. Edges are created anyway.

![error](https://user-images.githubusercontent.com/28961283/109967543-d9ebbd80-7cf1-11eb-9043-b0e1608715cc.jpg)


Another thing is that while testing and selecting Edges I notice that click on one Edge sometimes actually select another and sometimes select on curved part of edge  do nothing (it is not like clicking on wrong position, because it that case new node will appear). 

And even if everything will work fine, I would suggest an implementation I have in some my Google Map projects where clicking on polygons and polylines is also a problem to target with mouseclick, so a solution is, that you have two lines. One is thick, transparent and clickable and another is just for visualisation behind. At least this work fine in Google maps. 

I'm attaching 3 files. index.html have context menu disabled that right click on pane work. index.tsx and CustomNode.tsx are modification from useUpdateNodeInternals files.

[useupdatenodeinternals.zip](https://github.com/wbkd/react-flow/files/6083798/useupdatenodeinternals.zip)

**Comment by moklick** [comment]
could you check the new hook @andys8 ?

**Comment by moklick** [comment]
We will close this issue due to inactivity. Feel free to reopen it if the issue still occurs.

**Comment by sunWoodsen** [comment]
I had a similar problem. When I dynamically add a handler on a custom node, I find that the node's handlerDOM is updated, but when I create an edge for the node at the same time after the addition is successful, I find that the targetNode cannot be found (I specified targetNode), followed by I used useUpdateNodeInternals when the handler was successfully created. I found that getHandle still cannot get the latest handler dom. I suspect that there is a bug in the state synchronization.
![image](https://user-images.githubusercontent.com/39180485/149318262-ce50c5a0-87cd-4749-ad21-44db5c5adcf5.png)

here i can't get the latest handlers
